"""DeployConfigService — single source of truth for deploy config resolution.

Owns the resolution of every "what should this deploy actually do?"
question, drawing from three inputs:

1. The CLI-parsed :class:`DeployStackConfig` (the operator's
   arguments + env + profile-driven defaults).
2. The bootstrap-config JSON file referenced by ``cfg.config_file``
   (generated by ``media-stack-generate-bootstrap-config`` —
   contains the ``adapter_hooks`` tree, profile_actions, technology
   bindings, etc.).
3. Two compile-time registries — the auth provider registry and the
   edge provider registry — which give built-in defaults that
   adapter_hooks overrides can extend.

Before this service existed (pre-Phase-3 of ADR-0015), the same
logic was split across two parallel resolvers:
``cli/commands/deploy_stack_config_resolution.py`` (mixin) and
``cli/workflows/deploy_hook_config_resolver.py`` (service). Each
covered a partially overlapping set of hooks; the deploy CLI
silently disagreed with itself about required fields, surfacing as
the 2026-05-11 deploy-CLI bug chain. ADR-0015 Phase 3 consolidates
both into this single service in the workflows tier; the mixin and
its thin wrapper are deleted.

The class is constructor-injected with the operator's
:class:`DeployStackConfig` and the lower-level
:class:`DeployHookConfigResolverService` (which remains the
stateless "read this key out of the JSON" surface). This service is
stateful in exactly one place: it caches the parsed bootstrap-config
dict so repeat reads inside a single ``deploy_stack_main`` run
don't re-parse the JSON. Other state stays on the runner where it
already lives.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from media_stack.core.auth.provider_registry import (
    load_builtin_auth_provider_specs,
    merge_auth_provider_defaults,
)
from media_stack.core.controller_profile import load_bootstrap_profile_catalog
from media_stack.core.edge.provider_registry import (
    compose_label_specs_by_provider,
    router_service_names_by_provider,
)
from media_stack.core.logging_utils import log_swallowed
from media_stack.cli.commands.deploy_stack_errors import DeployError
from media_stack.cli.workflows.deploy_hook_config_resolver import (
    DeployHookConfigResolverService,
)

if TYPE_CHECKING:
    from media_stack.cli.workflows.deploy_cli_config_service import (
        DeployStackConfig,
    )


_TRUTHY_VALUES = frozenset({"1", "true", "yes", "on"})


class DeployConfigService:
    """Single resolver for everything ``DeployStackRunner`` needs to
    know about the deploy it's about to run.

    Owns the bootstrap-config cache so the runner doesn't need to
    pass it around or memoise it on the runner side. Delegates the
    stateless "read this slot out of the JSON" work to
    :class:`DeployHookConfigResolverService`; adds the cfg-overlay,
    registry-lookup, and validation work on top.
    """

    def __init__(
        self,
        cfg: "DeployStackConfig",
        *,
        hook_resolver: DeployHookConfigResolverService | None = None,
    ) -> None:
        self._cfg = cfg
        self._hook_resolver = hook_resolver or DeployHookConfigResolverService()
        self._bootstrap_cache: dict[str, object] | None = None

    # -- bootstrap config loading ------------------------------------------

    def resolved_bootstrap_config(self) -> dict[str, object]:
        """Return the parsed bootstrap-config JSON, cached on first read."""
        if self._bootstrap_cache is None:
            payload = json.loads(
                self._cfg.config_file.read_text(encoding="utf-8"),
            )
            if not isinstance(payload, dict):
                raise DeployError(
                    f"Expected JSON object in bootstrap config file: "
                    f"{self._cfg.config_file}",
                )
            self._bootstrap_cache = payload
        return self._bootstrap_cache

    def rebuild_profile_actions(
        self,
    ) -> tuple[
        dict[str, tuple[str, ...]],
        dict[str, tuple[str, ...]],
        dict[str, str],
        dict[str, tuple[str, ...]],
        tuple[str, ...],
        tuple[str, ...],
        tuple[str, ...],
    ]:
        try:
            return self._hook_resolver.profile_actions(
                self.resolved_bootstrap_config(),
            )
        except ValueError as exc:
            raise DeployError(str(exc)) from exc

    def adapter_hook_subkey(self, child_key: str) -> dict[str, object]:
        """Return ``adapter_hooks.<child_key>`` from the resolved config,
        or ``{}`` when either parent or child is missing / wrong type."""
        cfg = self.resolved_bootstrap_config()
        adapter_hooks = cfg.get("adapter_hooks")
        if not isinstance(adapter_hooks, dict):
            return {}
        section = adapter_hooks.get(child_key)
        if not isinstance(section, dict):
            return {}
        return section

    def bootstrap_job_hooks(self) -> dict[str, object]:
        return self.adapter_hook_subkey("bootstrap_job")

    def edge_hooks(self) -> dict[str, object]:
        return self.adapter_hook_subkey("edge")

    # -- edge routing resolution -------------------------------------------

    def ingress_class_priority(self) -> tuple[str, ...]:
        hooks = self.edge_hooks()
        raw = hooks.get("ingress_class_priority")
        if not isinstance(raw, list):
            return ()
        out: list[str] = []
        seen: set[str] = set()
        for item in raw:
            token = str(item or "").strip()
            if not token or token in seen:
                continue
            seen.add(token)
            out.append(token)
        return tuple(out)

    def edge_router_provider(self) -> str:
        explicit = str(self._cfg.edge_router_provider or "").strip().lower()
        if explicit:
            return explicit
        hooks = self.edge_hooks()
        return str(hooks.get("router_provider") or "").strip().lower()

    def _edge_provider_hook_values(
        self,
        *,
        by_provider_key: str,
        fallback_key: str,
    ) -> tuple[str, ...]:
        hooks = self.edge_hooks()
        provider = self.edge_router_provider()
        values: list[str] = []
        seen: set[str] = set()

        raw_by_provider = hooks.get(by_provider_key)
        selected_from_provider_map = False
        if isinstance(raw_by_provider, dict) and provider:
            provider_values = raw_by_provider.get(provider)
            if isinstance(provider_values, list):
                selected_from_provider_map = True
                for item in provider_values:
                    token = str(item or "").strip().lower()
                    if not token or token in seen:
                        continue
                    seen.add(token)
                    values.append(token)

        if not selected_from_provider_map:
            raw_fallback = hooks.get(fallback_key)
            if isinstance(raw_fallback, list):
                for item in raw_fallback:
                    token = str(item or "").strip().lower()
                    if not token or token in seen:
                        continue
                    seen.add(token)
                    values.append(token)

        return tuple(values)

    def edge_router_service_names(self) -> tuple[str, ...]:
        provider_defaults = router_service_names_by_provider()
        provider = self.edge_router_provider()
        out: list[str] = []
        seen: set[str] = set()
        for item in tuple(provider_defaults.get(provider) or ()):
            token = str(item or "").strip().lower()
            if not token or token in seen:
                continue
            seen.add(token)
            out.append(token)
        for item in self._edge_provider_hook_values(
            by_provider_key="router_service_names_by_provider",
            fallback_key="router_service_names",
        ):
            token = str(item or "").strip().lower()
            if not token or token in seen:
                continue
            seen.add(token)
            out.append(token)
        return tuple(out)

    def edge_path_prefix_redirect_service_names(self) -> tuple[str, ...]:
        # 1. Config.json override (per-deployment customization)
        out: list[str] = []
        seen: set[str] = set()
        for item in self._edge_provider_hook_values(
            by_provider_key="path_prefix_redirect_service_names_by_provider",
            fallback_key="path_prefix_redirect_service_names",
        ):
            token = str(item or "").strip().lower()
            if not token or token in seen:
                continue
            seen.add(token)
            out.append(token)
        if out:
            return tuple(out)
        # 2. Derive from per-service YAML registry (web_ui=true)
        try:
            from media_stack.core.service_registry.registry import (
                get_web_ui_services,
            )
            svcs = get_web_ui_services()
            if svcs:
                return tuple(s.id for s in svcs)
        except ImportError as exc:
            log_swallowed(exc)
        return ()

    def edge_path_prefix_preserve_service_names(self) -> tuple[str, ...]:
        # 1. Config.json override (per-deployment customization)
        out: list[str] = []
        seen: set[str] = set()
        for item in self._edge_provider_hook_values(
            by_provider_key="path_prefix_preserve_service_names_by_provider",
            fallback_key="path_prefix_preserve_service_names",
        ):
            token = str(item or "").strip().lower()
            if not token or token in seen:
                continue
            seen.add(token)
            out.append(token)
        if out:
            return tuple(out)
        # 2. Derive from per-service YAML registry (preserve_path_prefix=true)
        try:
            from media_stack.core.service_registry.registry import (
                get_preserve_path_prefix_services,
            )
            svcs = get_preserve_path_prefix_services()
            if svcs:
                return tuple(s.id for s in svcs)
        except ImportError as exc:
            log_swallowed(exc)
        return ()

    def edge_compose_provider_specs(self) -> dict[str, dict[str, str]]:
        out: dict[str, dict[str, str]] = {
            provider: dict(spec)
            for provider, spec in compose_label_specs_by_provider().items()
        }
        hooks = self.edge_hooks()
        raw = hooks.get("compose_provider_specs")
        if isinstance(raw, dict):
            for raw_provider, raw_spec in raw.items():
                provider = str(raw_provider or "").strip().lower()
                if not provider or not isinstance(raw_spec, dict):
                    continue
                merged_spec = dict(out.get(provider) or {})
                for raw_key, raw_value in raw_spec.items():
                    key = str(raw_key or "").strip()
                    value = str(raw_value or "").strip()
                    if key and value:
                        merged_spec[key] = value
                out[provider] = merged_spec
        return out

    def media_server_service_names(self) -> tuple[str, ...]:
        # 1. adapter_hooks.edge (config.json / K8s YAML)
        hooks = self.edge_hooks()
        raw = hooks.get("media_server_service_names")
        out: list[str] = []
        seen: set[str] = set()
        if isinstance(raw, list):
            for item in raw:
                token = str(item or "").strip().lower()
                if not token or token in seen:
                    continue
                seen.add(token)
                out.append(token)
        if out:
            return tuple(out)
        # 2. Profile YAML routing.media_server_service_names
        try:
            from media_stack.core.controller_profile import (
                load_bootstrap_profile,
            )
            profile = load_bootstrap_profile()
            routing = profile.get("routing") or {}
            raw_profile = routing.get("media_server_service_names")
            if isinstance(raw_profile, list) and raw_profile:
                return tuple(
                    str(s).strip().lower()
                    for s in raw_profile
                    if str(s).strip()
                )
        except (ImportError, ValueError, OSError) as exc:
            log_swallowed(exc)
        # 3. Derive from technology_bindings
        cfg = self.resolved_bootstrap_config()
        technology_bindings = cfg.get("technology_bindings")
        if isinstance(technology_bindings, dict):
            token = str(technology_bindings.get("media_server") or "").strip().lower()
            if token:
                return (token,)
        return ()

    # -- auth / route / provider validation --------------------------------

    def auth_provider_middleware_defaults(self) -> dict[str, str]:
        catalog = load_bootstrap_profile_catalog()
        hooks = self.edge_hooks()
        hook_defaults: dict[str, str] = {}
        raw = hooks.get("auth_provider_middleware_defaults")
        if isinstance(raw, dict):
            for raw_key, raw_value in raw.items():
                key = str(raw_key or "").strip().lower()
                if not key:
                    continue
                hook_defaults[key] = str(raw_value or "").strip()

        provider_keys: list[str] = []
        seen: set[str] = set()
        for raw_key in (
            *tuple(catalog.auth_providers),
            str(catalog.auth_disabled_provider or "").strip().lower(),
            *(spec.key for spec in load_builtin_auth_provider_specs()),
            *tuple(hook_defaults.keys()),
        ):
            key = str(raw_key or "").strip().lower()
            if not key or key in seen:
                continue
            seen.add(key)
            provider_keys.append(key)
        return merge_auth_provider_defaults(
            provider_keys=tuple(provider_keys),
            catalog_defaults=dict(catalog.auth_provider_middleware_defaults or {}),
            override_defaults=hook_defaults,
        )

    def valid_route_strategies(self) -> tuple[str, ...]:
        catalog = load_bootstrap_profile_catalog()
        values = tuple(dict.fromkeys(catalog.route_strategy_aliases.values()))
        return tuple(
            str(value).strip().lower()
            for value in values
            if str(value).strip()
        )

    def valid_auth_providers(self) -> tuple[str, ...]:
        catalog = load_bootstrap_profile_catalog()
        values: list[str] = []
        seen: set[str] = set()
        for token in (
            *tuple(catalog.auth_providers),
            str(catalog.auth_disabled_provider or "").strip().lower(),
            *tuple(self.auth_provider_middleware_defaults().keys()),
        ):
            normalized = str(token or "").strip().lower()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            values.append(normalized)
        return tuple(values)

    def valid_edge_router_providers(self) -> tuple[str, ...]:
        providers = {
            str(provider or "").strip().lower()
            for provider in self.edge_compose_provider_specs().keys()
            if str(provider or "").strip()
        }
        return tuple(sorted(providers))

    # -- bootstrap job / policy config -------------------------------------

    def runtime_config_policy_handler_spec(self) -> str:
        hooks = self.bootstrap_job_hooks()
        spec = str(hooks.get("runtime_config_policy_handler") or "").strip()
        if spec and ":" not in spec:
            raise DeployError(
                "adapter_hooks.bootstrap_job.runtime_config_policy_handler "
                "must be module.path:Symbol",
            )
        return spec

    def runtime_config_policy_params(self) -> dict[str, object]:
        return {
            "selected_apps_csv": self._cfg.selected_apps,
            "preconfigure_api_keys": self._is_truthy(self._cfg.preconfigure_api_keys),
            "auto_download_content": self._is_truthy(self._cfg.auto_download_content),
            "internet_exposed": self._is_truthy(self._cfg.internet_exposed),
            "route_strategy": self._cfg.route_strategy,
            "auth_provider": self._cfg.auth_provider,
            "auth_middleware": self._cfg.auth_middleware,
            "edge_router_provider": self.edge_router_provider(),
            "ingress_domain": self._cfg.ingress_domain,
            "app_gateway_host": self._cfg.app_gateway_host,
            "app_gateway_port": self._cfg.app_gateway_port,
            "app_path_prefix": self._cfg.app_path_prefix,
            "media_server_direct_host": self._cfg.media_server_direct_host,
        }

    def compose_passthrough_env_vars(self) -> tuple[str, ...]:
        env_vars: list[str] = ["STACK_ADMIN_USERNAME", "STACK_ADMIN_PASSWORD"]
        hooks = self.bootstrap_job_hooks()
        secret_targets = hooks.get("secret_priming_targets")
        if isinstance(secret_targets, dict):
            for spec in secret_targets.values():
                if not isinstance(spec, dict):
                    continue
                name = str(spec.get("env_var") or "").strip()
                if name:
                    env_vars.append(name)
        deduped: list[str] = []
        seen: set[str] = set()
        for raw_name in env_vars:
            name = str(raw_name or "").strip()
            if not name or name in seen:
                continue
            seen.add(name)
            deduped.append(name)
        return tuple(deduped)

    def compose_preflight_handlers(self) -> tuple[str, ...]:
        try:
            return self._hook_resolver.compose_preflight_handlers(
                self.bootstrap_job_hooks(),
            )
        except ValueError as exc:
            raise DeployError(str(exc)) from exc

    # -- helpers ----------------------------------------------------------

    def _is_truthy(self, value: str) -> bool:
        return str(value or "").strip().lower() in _TRUTHY_VALUES


__all__ = ["DeployConfigService"]
