// Typed wrappers around the controller endpoints the dashboard calls.
// Each function returns a typed promise; mutations accept an optional
// idempotency key (auto-generated by `fetcher` when omitted).
//
// When `pnpm gen:api` produces real `components["schemas"]` types, the
// shape aliases below should be swapped for the generated equivalents
// and `shapes.ts` deleted.

import { fetcher } from "./client";
import type {
  AuditLogShape,
  BrandingShape,
  EnforceReportShape,
  HealthShape,
  IdentityShape,
  LogSource,
  LogStreamShape,
  MediaIntegrityProgressShape,
  MediaIntegrityStatusShape,
  ReconcileReportShape,
  ResolveReviewInput,
  ResolveReviewOutput,
  SessionsShape,
} from "./shapes";

interface MutationOpts {
  idempotencyKey?: string;
}

interface ReconcileOpts extends MutationOpts {
  dryRun?: boolean;
}

interface AuditLogOpts {
  limit?: number;
  action?: string;
}

function withIdem(opts?: MutationOpts): { idempotencyKey?: string } {
  return opts?.idempotencyKey !== undefined
    ? { idempotencyKey: opts.idempotencyKey }
    : {};
}

export const api = {
  health: (): Promise<HealthShape> => fetcher<HealthShape>("api/health"),

  branding: (): Promise<BrandingShape> =>
    fetcher<BrandingShape>("api/branding"),

  auth: {
    identity: (): Promise<IdentityShape> =>
      fetcher<IdentityShape>("api/auth/identity"),
    logout: (opts?: MutationOpts): Promise<void> =>
      fetcher<void>("api/auth/logout", { method: "POST", ...withIdem(opts) }),
  },

  mediaIntegrity: {
    status: (): Promise<MediaIntegrityStatusShape> =>
      fetcher<MediaIntegrityStatusShape>("api/media-integrity/status"),

    progress: (): Promise<MediaIntegrityProgressShape> =>
      fetcher<MediaIntegrityProgressShape>("api/media-integrity/progress"),

    reconcile: (opts?: ReconcileOpts): Promise<ReconcileReportShape> =>
      fetcher<ReconcileReportShape>(
        `api/media-integrity/reconcile${opts?.dryRun ? "?dry_run=1" : ""}`,
        { method: "POST", ...withIdem(opts) },
      ),

    enforceConfig: (opts?: MutationOpts): Promise<EnforceReportShape> =>
      fetcher<EnforceReportShape>("api/media-integrity/enforce-config", {
        method: "POST",
        ...withIdem(opts),
      }),

    resolveReview: (
      body: ResolveReviewInput,
      opts?: MutationOpts,
    ): Promise<ResolveReviewOutput> =>
      fetcher<ResolveReviewOutput>("api/media-integrity/resolve-review", {
        method: "POST",
        body: JSON.stringify(body),
        ...withIdem(opts),
      }),
  },

  auditLog: (opts?: AuditLogOpts): Promise<AuditLogShape> => {
    const params = new URLSearchParams();
    params.set("limit", String(opts?.limit ?? 50));
    if (opts?.action) params.set("action", opts.action);
    return fetcher<AuditLogShape>(`api/audit-log?${params.toString()}`);
  },

  sessions: (): Promise<SessionsShape> =>
    fetcher<SessionsShape>("api/sessions/active"),

  // TODO(api): real /api/logs/stream endpoint with SSE; for now we
  // wrap the GET so consumers stay typed once it lands.
  logs: (source: LogSource): Promise<LogStreamShape> =>
    fetcher<LogStreamShape>(`api/logs/${encodeURIComponent(source)}`),

  // System-level operations triggered from the Ops tab. Paths match
  // the controller's OpenAPI spec verbatim — earlier shapes
  // (`/api/keys/rotate`, `/api/services/refresh`, `/api/manifests/pull`,
  // `/api/health/probe`) were 404s.
  //
  // `refreshServices` and `healthProbe` are read-side: the UI just
  // re-fetches the relevant queries via React Query invalidation
  // rather than calling a dedicated POST. `pullManifests` reads
  // `GET /api/manifests` (the controller refreshes from upstream as
  // part of the read).
  ops: {
    rotateKeys: (opts?: MutationOpts): Promise<void> =>
      fetcher<void>("api/rotate-keys", { method: "POST", ...withIdem(opts) }),
    pullManifests: (): Promise<unknown> =>
      fetcher<unknown>("api/manifests"),
  },
} as const;

export type Api = typeof api;
