"""BootstrapConfigLoader — Repository pattern for the deploy bootstrap config.

Owns the on-disk representation of the bootstrap config JSON file
(``contracts/media-stack.config.json`` generated by
``media-stack-generate-bootstrap-config``) plus the typed views into
it that every other deploy_config resolver needs:

* The whole parsed dict (cached on first read).
* The ``adapter_hooks.<key>`` sub-trees the operator's profile YAML
  was translated into.
* The 7-tuple ``profile_actions`` that the legacy hook-resolver
  service emits — delegates to
  :class:`DeployHookConfigResolverService` for the actual tuple
  shape conversion.

Repository pattern: this class is the single point of access to
the bootstrap config JSON. Other resolvers (edge, auth, runtime
policy, compose) constructor-inject this loader and call its
public methods — they don't touch the file system or the JSON
text. That keeps the "where does the config come from?" decision
in one place and means tests can substitute a fake loader without
patching ``Path.read_text`` or the file system.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from media_stack.cli.workflows.deploy_errors import DeployError
from media_stack.cli.workflows.deploy_hook_config_resolver import (
    DeployHookConfigResolverService,
)

if TYPE_CHECKING:
    from media_stack.cli.workflows.deploy_cli_config_service import (
        DeployStackConfig,
    )


class BootstrapConfigLoader:
    """Repository: the parsed bootstrap-config JSON + typed sub-tree views."""

    def __init__(
        self,
        cfg: "DeployStackConfig",
        *,
        hook_resolver: DeployHookConfigResolverService | None = None,
    ) -> None:
        self._cfg = cfg
        self._hook_resolver = hook_resolver or DeployHookConfigResolverService()
        self._cache: dict[str, object] | None = None

    def resolved(self) -> dict[str, object]:
        """Return the parsed bootstrap-config JSON, cached on first read."""
        if self._cache is None:
            payload = json.loads(
                self._cfg.config_file.read_text(encoding="utf-8"),
            )
            if not isinstance(payload, dict):
                raise DeployError(
                    f"Expected JSON object in bootstrap config file: "
                    f"{self._cfg.config_file}",
                )
            self._cache = payload
        return self._cache

    def adapter_hook_subkey(self, child_key: str) -> dict[str, object]:
        """Return ``adapter_hooks.<child_key>`` from the resolved config,
        or ``{}`` when either parent or child is missing / wrong type."""
        cfg = self.resolved()
        adapter_hooks = cfg.get("adapter_hooks")
        if not isinstance(adapter_hooks, dict):
            return {}
        section = adapter_hooks.get(child_key)
        if not isinstance(section, dict):
            return {}
        return section

    def bootstrap_job_hooks(self) -> dict[str, object]:
        return self.adapter_hook_subkey("bootstrap_job")

    def edge_hooks(self) -> dict[str, object]:
        return self.adapter_hook_subkey("edge")

    def profile_actions(
        self,
    ) -> tuple[
        dict[str, tuple[str, ...]],
        dict[str, tuple[str, ...]],
        dict[str, str],
        dict[str, tuple[str, ...]],
        tuple[str, ...],
        tuple[str, ...],
        tuple[str, ...],
    ]:
        """7-tuple of profile-driven settings, decoded from JSON.

        Delegates to :class:`DeployHookConfigResolverService` for the
        tuple shape — that service stays the canonical "shape of a
        bootstrap config" oracle; the loader just hands it the dict.
        ``ValueError`` from the resolver is translated to
        :class:`DeployError` here because deploy-flow callers expect
        the deploy-namespaced exception type.
        """
        try:
            return self._hook_resolver.profile_actions(self.resolved())
        except ValueError as exc:
            raise DeployError(str(exc)) from exc


__all__ = ["BootstrapConfigLoader"]
