#!/usr/bin/env bash
# Deploy media stack via Docker Compose — single command.
#
# Usage:
#   ./deploy-compose.sh                Deploy (idempotent — works on
#                                      first run or re-run).
#   ./deploy-compose.sh --delete       Teardown + redeploy from scratch.
#   ./deploy-compose.sh init           Pre-flight checks only — verify
#                                      docker, ports, generate secrets.
#                                      Does NOT start anything.
#   ./deploy-compose.sh status         Print credentials + URLs (without
#                                      redeploying).
#
# Env overrides:
#   BOOTSTRAP_RUNNER_IMAGE=…           Pin a controller image
#   UI_RUNNER_IMAGE=…                  Pin a UI image
#   QBITTORRENT_PUBLISHED_PORT=8082    Move qbittorrent off the
#                                      default 8080 if another tool
#                                      (kubectl, minikube, dev server)
#                                      already binds it.
#
# Flow (no flags):
#   1. Pre-flight checks (init step, idempotent)
#   2. Start every service
#   3. Wait for controller health
#   4. Trigger bootstrap via HTTP API
#   5. Poll status until complete
#   6. Print sign-in credentials + dashboard URL

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/deploy/compose/docker-compose.yml"
SECRETS_FILE="$SCRIPT_DIR/secrets.generated.env"
BOOTSTRAP_PORT="${BOOTSTRAP_API_PORT:-9100}"
UI_PORT_DEFAULT="${UI_PORT:-9101}"

# ---------- helpers ----------

log() { echo "$*"; }
err() { echo "  ERROR: $*" >&2; }

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "$1 not found on PATH. Install it before running this script."
        exit 2
    fi
}

ensure_docker() {
    require_command docker
    if ! docker info >/dev/null 2>&1; then
        err "docker daemon is not reachable. Is the Docker engine running?"
        exit 2
    fi
    if ! docker compose version >/dev/null 2>&1; then
        err "docker compose v2 plugin not found. Upgrade docker so 'docker compose' works."
        exit 2
    fi
}

# Bind-test a port — the cheapest way to check whether something
# else is already listening on it. We only WARN; the user can
# override with QBITTORRENT_PUBLISHED_PORT etc. or skip the test
# by setting SKIP_PREFLIGHT_PORTS=1.
check_port_free() {
    local port="$1"
    local label="$2"
    if [[ "${SKIP_PREFLIGHT_PORTS:-}" == "1" ]]; then
        return 0
    fi
    # Use python's socket binding so we don't depend on netstat / ss.
    local in_use
    in_use=$(python3 -c "
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    s.bind(('0.0.0.0', $port))
    print('free')
except OSError:
    print('in_use')
finally:
    s.close()
" 2>/dev/null || echo "free")
    if [[ "$in_use" == "in_use" ]]; then
        log "  WARN: port ${port} (${label}) is already in use. Set ${label}=<other> to override or stop the process binding it."
    fi
}

ensure_secrets() {
    if [[ ! -f "$SECRETS_FILE" ]] || ! grep -q "^STACK_ADMIN_PASSWORD=.\{16,\}" "$SECRETS_FILE"; then
        log "Generating ${SECRETS_FILE} with a random admin password..."
        RANDOM_PW=$(python3 -c "import secrets;print(secrets.token_urlsafe(24))")
        {
            echo "# Generated by deploy-compose.sh"
            echo "# Rotate the password from the dashboard /me — env-fallback"
            echo "# stops working as soon as you do."
            echo "STACK_ADMIN_USERNAME=admin"
            echo "STACK_ADMIN_PASSWORD=${RANDOM_PW}"
        } > "$SECRETS_FILE"
        chmod 600 "$SECRETS_FILE"
        log "  Admin credentials written to ${SECRETS_FILE} (600)"
    fi
    # Source so docker-compose's ${STACK_ADMIN_PASSWORD:-...} resolves.
    # shellcheck disable=SC1090
    set -a; source "$SECRETS_FILE"; set +a
}

print_status_banner() {
    log ""
    log "================================================================"
    log "Deploy complete."
    log "================================================================"
    log ""
    log "  Dashboard:  http://127.0.0.1:${UI_PORT_DEFAULT}/"
    log "  Homepage:   http://127.0.0.1:80/app/homepage (via Envoy)"
    log ""
    log "  First-login credentials (from ${SECRETS_FILE}):"
    log "    Username: ${STACK_ADMIN_USERNAME}"
    log "    Password: ${STACK_ADMIN_PASSWORD}"
    log ""
    log "  These are seed values. After your first sign-in, rotate"
    log "  the password from /me — the env-seed stops working as soon"
    log "  as you do (source flips from env-legacy to rotated). The"
    log "  file above is a one-time-use record, not a live secret."
    log ""
    log "  Controller API (REST only):"
    log "    http://127.0.0.1:${BOOTSTRAP_PORT}/api/me"
    log "    Trigger: curl -X POST http://127.0.0.1:${BOOTSTRAP_PORT}/actions/bootstrap"
    log "================================================================"
}

# ---------- subcommands ----------

cmd_init() {
    log "Pre-flight checks for compose deploy..."
    ensure_docker
    log "  ✓ docker engine + docker compose v2"
    check_port_free 80   "TRAEFIK_HTTP_PORT (compose: 80)"
    check_port_free 443  "TRAEFIK_HTTPS_PORT (compose: 443)"
    check_port_free 8080 "QBITTORRENT_PUBLISHED_PORT"
    check_port_free 9100 "BOOTSTRAP_API_PORT (controller)"
    check_port_free 9101 "UI_PORT (dashboard)"
    ensure_secrets
    log "  ✓ secrets generated"
    log ""
    log "Pre-flight passed. Run './deploy-compose.sh' to bring the stack up."
}

cmd_status() {
    if [[ ! -f "$SECRETS_FILE" ]]; then
        err "${SECRETS_FILE} not found. Run './deploy-compose.sh init' first."
        exit 2
    fi
    # shellcheck disable=SC1090
    set -a; source "$SECRETS_FILE"; set +a
    print_status_banner
}

cmd_deploy() {
    ensure_docker
    ensure_secrets

    log "Compose deploy: starting services..."
    docker compose -f "$COMPOSE_FILE" up -d

    # Wait for controller service to be healthy.
    log "  Waiting for controller service..."
    HEALTH=""
    for _ in $(seq 1 40); do
        HEALTH=$(curl -sf "http://127.0.0.1:${BOOTSTRAP_PORT}/healthz" 2>/dev/null || echo "")
        [[ -n "$HEALTH" ]] && break
        sleep 3
    done
    if [[ -z "$HEALTH" ]]; then
        err "Controller service not responding on port ${BOOTSTRAP_PORT} within 120s"
        exit 1
    fi
    log "  Controller service ready."

    # Trigger bootstrap via HTTP API.
    log "  Triggering bootstrap..."
    curl -sf -X POST "http://127.0.0.1:${BOOTSTRAP_PORT}/actions/bootstrap" \
        -H "Content-Type: application/json" -d '{}' >/dev/null || true

    # Poll status until complete.
    log "  Polling bootstrap status..."
    PHASE=""
    for _ in $(seq 1 60); do
        PHASE=$(curl -sf "http://127.0.0.1:${BOOTSTRAP_PORT}/status" 2>/dev/null | \
            python3 -c "import json,sys; print(json.load(sys.stdin).get('phase',''))" 2>/dev/null || echo "")
        [[ "$PHASE" == "complete" ]] && log "  Bootstrap: complete" && break
        [[ "$PHASE" == "error" ]] && log "  Bootstrap: error (check dashboard)" && break
        sleep 10
    done

    print_status_banner
}

# ---------- entry point ----------

# Handle --delete BEFORE subcommand parsing.
if [[ "${1:-}" == "--delete" ]]; then
    log "Tearing down compose stack..."
    docker compose -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
    shift || true
fi

case "${1:-deploy}" in
    init)
        cmd_init
        ;;
    status)
        cmd_status
        ;;
    deploy|"")
        cmd_deploy
        ;;
    -h|--help)
        head -n 30 "$0" | sed 's/^# \?//'
        ;;
    *)
        err "Unknown subcommand: ${1}. Try: init | status | deploy | --delete"
        exit 2
        ;;
esac
