"""Servarr-family implementation of ``ServiceLifecycle``.

One class parameterized by ``service_id`` covers sonarr, radarr,
lidarr, readarr, and prowlarr. They share an identical lifecycle
shape:

  * Health probe at ``/ping``
  * API key in ``<ApiKey>X</ApiKey>`` inside ``config.xml``, auto-
    generated by the *arr process on first start (no REST mint)
  * Single canonical XML reader/writer in
    ``api.services.key_formats``

Bazarr is intentionally NOT covered here — it uses YAML config and a
REST settings flow, not the auto-generated config.xml pattern, and
has its own ``BazarrLifecycle``.

"Mint" semantics for Servarr: there is no mint endpoint. The *arr
process generates a random key on first start and writes it to
``config.xml``. So ``mint_api_key`` is "wait for the file" — if the
file doesn't exist yet (service still warming up), return
``transient=True`` so the orchestrator retries on the next auto-heal
tick. If the file exists but has no key tag, that's a structural
problem and we return ``transient=False``.
"""

from __future__ import annotations

import logging
import os
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from media_stack.adapters.servarr.download_client_wiring import (
    DownloadClientWirer,
)
from media_stack.adapters.servarr.indexer_pipeline import (
    IndexerPipelineWirer,
)
from media_stack.adapters.servarr.notifier_wiring import (
    JellyfinNotifierWirer,
)
from media_stack.adapters.servarr.runtime_defaults_wiring import (
    RuntimeDefaultsWirer,
)
from media_stack.adapters.servarr.seed_series_wiring import (
    SeedSeriesWirer,
)
from media_stack.domain.services import (
    OrchestrationContext,
    Outcome,
    ProbeResult,
    ServiceLifecycle,
)


logger = logging.getLogger(__name__)


_SUPPORTED_SERVICE_IDS = frozenset(
    {"sonarr", "radarr", "lidarr", "readarr", "prowlarr"}
)
_DEFAULT_HEALTH_PATH = "/ping"
_DEFAULT_PROBE_TIMEOUT_SECONDS = 5
_DEFAULT_API_KEY_FORMAT = "xml"

# Stateless module-level singleton — the wirer is per-call
# parameterized by service_id + arr_api_key + ctx, so one instance
# handles every *arr. Constructor-injected notifier identity (name /
# host / port) keeps the magic-number / duplicate-string surface in
# the wirer module rather than here.
_JELLYFIN_NOTIFIER_WIRER = JellyfinNotifierWirer()

# Same shape as the notifier wirer above — stateless module-level
# singleton, per-call parameterized by service_id + arr_api_key +
# ctx. Constructor-injected Prowlarr identity (host / port) keeps
# the magic-number / duplicate-string surface in the wirer module.
_INDEXER_PIPELINE_WIRER = IndexerPipelineWirer()

# Same shape — stateless module-level singleton. The seed-series
# wirer is Sonarr-only (other *arrs short-circuit) and uses the
# Jellyseerr wide-handler delegation pattern: probe is owned, but
# ensure delegates to the legacy handler via injected callables so
# ~100 LoC of multi-subsystem orchestration isn't duplicated here.
_SEED_SERIES_WIRER = SeedSeriesWirer()

# Same shape — stateless module-level singleton, per-call
# parameterized by service_id + arr_api_key + ctx. Per the Bazarr
# monolithic-handler lesson, the runtime-defaults wirer owns N
# distinct probes (quality-profiles + import-lists-auto) but ONE
# shared ensurer that delegates to the legacy
# ``apply_arr_runtime_defaults`` handler — same wide-handler
# delegation pattern the Jellyseerr family uses, because the legacy
# handler does ~100 LoC of multi-arr orchestration in one pass and
# splitting into N ensurers would clobber the shared *arr settings.
_RUNTIME_DEFAULTS_WIRER = RuntimeDefaultsWirer()

# ADR-0005 Phase 5b — the deferred 9th wirer. Same shape as the
# notifier / indexer-pipeline / seed-series instances above:
# stateless module-level singleton, per-call parameterized by
# service_id + arr_api_key + ctx. qBittorrent identity (host /
# port / creds) is constructor-injected so tests can override
# without touching process env. Two promises bind:
# sonarr-download-client (cat=tv) + radarr-download-client
# (cat=movies); lidarr / readarr have no download-client promise
# today but the wirer covers them so the same lifecycle method
# works across the family.
_DOWNLOAD_CLIENT_WIRER = DownloadClientWirer()


class ServarrLifecycle:
    """``ServiceLifecycle`` implementation for the Servarr family.

    Constructor takes the ``service_id`` ("sonarr", "radarr", ...)
    and stores it as the instance attribute the Protocol requires.
    The same class instance is per-service: bootstrapping all five
    *arr services means five ``ServarrLifecycle`` instances, one each.

    Stateless beyond ``service_id``; per-call config flows through
    ``OrchestrationContext.config``.
    """

    def __init__(self, service_id: str) -> None:
        sid = (service_id or "").strip().lower()
        if sid not in _SUPPORTED_SERVICE_IDS:
            raise ValueError(
                f"ServarrLifecycle: unsupported service_id={service_id!r}; "
                f"expected one of {sorted(_SUPPORTED_SERVICE_IDS)}. Bazarr "
                "uses BazarrLifecycle (Phase 3); for Jellyfin use "
                "JellyfinLifecycle.",
            )
        self.service_id = sid

    # --- probes -----------------------------------------------------

    def probe_running(self, ctx: OrchestrationContext) -> ProbeResult:
        url = self._ping_url(ctx)
        if not url:
            return ProbeResult.failed(
                "no host/port in config — cannot probe",
                evidence={"config_keys": sorted(ctx.config.keys())},
                evaluated_at=ctx.now(),
            )
        try:
            with urllib.request.urlopen(
                url, timeout=_DEFAULT_PROBE_TIMEOUT_SECONDS,
            ) as resp:
                if resp.status == 200:
                    return ProbeResult.ok(
                        f"responsive at {url}",
                        evidence={"http_status": 200, "url": url},
                        evaluated_at=ctx.now(),
                    )
                return ProbeResult.failed(
                    f"non-200 from {url}: {resp.status}",
                    evidence={"http_status": resp.status, "url": url},
                    evaluated_at=ctx.now(),
                )
        except urllib.error.HTTPError as exc:
            return ProbeResult.failed(
                f"HTTP {exc.code} from {url}",
                evidence={"http_status": exc.code, "url": url},
                evaluated_at=ctx.now(),
            )
        except (urllib.error.URLError, OSError, TimeoutError) as exc:
            return ProbeResult.unknown(
                f"unreachable at {url}: {exc}",
                evidence={"url": url, "error": str(exc)},
                evaluated_at=ctx.now(),
            )

    def probe_has_api_key(self, ctx: OrchestrationContext) -> ProbeResult:
        key = self.discover_api_key(ctx)
        if key:
            return ProbeResult.ok(
                "api key discoverable",
                evidence={
                    "key_length": len(key),
                    "source": _classify_source(ctx, key),
                },
                evaluated_at=ctx.now(),
            )
        return ProbeResult.failed(
            "no api key in env or config.xml",
            evidence={
                "env_var_checked": _api_key_env(ctx),
                "config_path": str(_config_path(ctx)),
            },
            evaluated_at=ctx.now(),
        )

    # --- discover ---------------------------------------------------

    def discover_api_key(self, ctx: OrchestrationContext) -> str | None:
        env_var = _api_key_env(ctx)
        env_value = (ctx.secrets.get(env_var) or os.environ.get(env_var) or "").strip()
        if env_value:
            return env_value

        config_path = _config_path(ctx)
        if not config_path or not config_path.is_file():
            return None

        from media_stack.api.services.key_formats import READERS
        fmt = (ctx.config.get("api_key_format") or _DEFAULT_API_KEY_FORMAT).lower()
        reader = READERS.get(fmt)
        if reader is None:
            logger.debug(
                "discover_api_key: no reader for format=%r (service=%s)",
                fmt, self.service_id,
            )
            return None
        try:
            value = reader(config_path)
        except Exception as exc:  # noqa: BLE001
            logger.debug(
                "discover_api_key: %s reader raised: %s", fmt, exc,
            )
            return None
        return value.strip() if value else None

    # --- mint -------------------------------------------------------

    def mint_api_key(self, ctx: OrchestrationContext) -> Outcome[str]:
        # Idempotent short-circuit — the *arr process auto-generates,
        # so if the file already has a key, nothing to do.
        existing = self.discover_api_key(ctx)
        if existing:
            return Outcome.success(
                existing,
                attempts=0,
                evidence={"reason": "already_discoverable"},
            )

        config_path = _config_path(ctx)
        if not config_path:
            return Outcome.failure(
                "no api_key_config path in config — cannot mint",
                transient=False,
                evidence={"config_keys": sorted(ctx.config.keys())},
            )
        if not config_path.is_file():
            # Service hasn't generated the file yet. This is the
            # warmup case — auto-heal will retry; nothing actionable
            # for the operator unless the service stays unhealthy.
            return Outcome.failure(
                f"{self.service_id} config.xml not yet generated at {config_path}",
                transient=True,
                evidence={
                    "config_path": str(config_path),
                    "service_id": self.service_id,
                },
            )

        # File exists but no key — that's structural, not transient.
        # The *arr process should write the key on first start; if it
        # didn't, manual investigation is needed.
        return Outcome.failure(
            f"{self.service_id} config.xml present but <ApiKey> missing",
            transient=False,
            evidence={
                "config_path": str(config_path),
                "service_id": self.service_id,
            },
        )

    # --- Jellyfin notifier wiring (ADR-0005 Phase 3) ----------------
    #
    # Both methods delegate to ``JellyfinNotifierWirer`` (in
    # ``notifier_wiring.py``). The lifecycle owns the api-key
    # discovery contract; the wirer owns the HTTP / payload shape.

    def probe_jellyfin_notifier(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _JELLYFIN_NOTIFIER_WIRER.probe(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def ensure_jellyfin_notifier(
        self, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        return _JELLYFIN_NOTIFIER_WIRER.ensure(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    # --- Indexer-pipeline wiring (ADR-0005 Phase 3 follow-on) -------
    #
    # Both methods delegate to ``IndexerPipelineWirer`` (in
    # ``indexer_pipeline.py``). The lifecycle owns the api-key
    # discovery contract; the wirer owns the per-arr indexer-list
    # HTTP shape and the Prowlarr ``ApplicationIndexerSync``
    # trigger.

    def probe_has_indexers(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _INDEXER_PIPELINE_WIRER.probe(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def ensure_indexers(
        self, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        return _INDEXER_PIPELINE_WIRER.ensure(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    # --- Seed-series wiring (ADR-0005 Phase 3 — wide-handler) -------
    #
    # The seed-series wirer's probe is owned (count Sonarr's series,
    # idempotent skip when sufficient); the ensurer delegates to the
    # legacy ``ensure_sonarr_seed_series`` handler via injected
    # callables. The legacy handler is wide (~100 LoC: read seed
    # config, fetch qualityprofile + rootfolder + existing series,
    # tvdbId-lookup per seed name, POST each new series). Following
    # the Jellyseerr addendum, we keep that handler as the
    # implementation rather than duplicating it inside the wirer.
    #
    # Lazy imports go through the ``services/`` shim path so the
    # adapters → application hexagon ratchet stays clean — the
    # canonical ``application.jobs.framework`` module is reached
    # transitively via the shim, not by direct import here. Same
    # convention the Jellyseerr arr-servers ensurer follows.

    def probe_has_series(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _SEED_SERIES_WIRER.probe(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def ensure_has_series(
        self, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        from media_stack.services.apps.core.job_adapters import (
            ensure_sonarr_seed_series,
        )
        from media_stack.services.jobs.framework import JobContext
        return _SEED_SERIES_WIRER.ensure(
            self.service_id, self.discover_api_key(ctx), ctx,
            configure_handler=ensure_sonarr_seed_series,
            job_context_factory=JobContext,
        )

    # --- Runtime-defaults wiring (ADR-0005 Phase 3) -----------------
    #
    # Three promises bind here:
    #   * sonarr-quality-profiles    → probe_quality_profiles
    #   * radarr-quality-profiles    → probe_quality_profiles
    #   * radarr-import-lists-auto   → probe_import_lists_auto
    # All three share ``ensure_runtime_defaults`` (rationale on the
    # wirer module top: legacy handler is monolithic — splitting into
    # per-promise ensurers would mean three POST runs that each
    # clobber the shared *arr settings document).
    #
    # ``probe_import_lists_auto`` short-circuits ``ok`` for non-radarr
    # service ids using the unsupported-service pattern from
    # ``JellyfinNotifierWirer``; sonarr lifecycle instances will never
    # have a promise that calls it, but the wirer guards anyway.

    def probe_quality_profiles(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _RUNTIME_DEFAULTS_WIRER.probe_quality_profiles(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def probe_import_lists_auto(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _RUNTIME_DEFAULTS_WIRER.probe_import_lists_auto(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def ensure_runtime_defaults(
        self, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        return _RUNTIME_DEFAULTS_WIRER.ensure_runtime_defaults(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    # --- Download-client wiring (ADR-0005 Phase 5b) -----------------
    #
    # Two promises bind:
    #   * sonarr-download-client → probe_download_client / ensure
    #   * radarr-download-client → probe_download_client / ensure
    #
    # Both methods delegate to ``DownloadClientWirer`` (in
    # ``download_client_wiring.py``). The lifecycle owns the api-key
    # discovery contract; the wirer owns the per-arr endpoint shape,
    # the qBittorrent payload, and the upsert-by-implementation
    # match logic.
    #
    # Lidarr / Readarr have no download-client promise today, but
    # the wirer's ``_ARR_DOWNLOAD_CLIENT_SPECS`` table covers them
    # too — so adding a future ``lidarr-download-client`` promise is
    # a one-line YAML change rather than a wirer rewrite.

    def probe_download_client(
        self, ctx: OrchestrationContext,
    ) -> ProbeResult:
        return _DOWNLOAD_CLIENT_WIRER.probe(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    def ensure_download_client(
        self, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        return _DOWNLOAD_CLIENT_WIRER.ensure(
            self.service_id, self.discover_api_key(ctx), ctx,
        )

    # --- persist ----------------------------------------------------

    def persist_api_key(
        self, key: str, ctx: OrchestrationContext,
    ) -> Outcome[None]:
        env_var = _api_key_env(ctx)
        if not key:
            return Outcome.failure(
                "refusing to persist empty key",
                transient=False,
                evidence={"env_var": env_var},
            )
        os.environ[env_var] = key

        try:
            from media_stack.services.apps.core.job_adapters import (
                _persist_preflight_keys_to_secret_safe,
                _stub_state,
            )
            secret_result = _persist_preflight_keys_to_secret_safe(
                _stub_state(), {env_var: key},
            )
            return Outcome.success(
                evidence={
                    "env_written": env_var,
                    "secret_status": str(
                        (secret_result or {}).get("status") or secret_result,
                    ),
                },
            )
        except Exception as exc:  # noqa: BLE001
            return Outcome.failure(
                f"env written; secret patch failed: {exc}",
                transient=True,
                evidence={"env_written": env_var, "error": str(exc)},
            )

    # --- helpers ----------------------------------------------------

    def _ping_url(self, ctx: OrchestrationContext) -> str:
        host = (ctx.config.get("host") or "").strip()
        port = ctx.config.get("port")
        if not host or not port:
            return ""
        scheme = (ctx.config.get("scheme") or "http").strip()
        path = ctx.config.get("health_path") or _DEFAULT_HEALTH_PATH
        return f"{scheme}://{host}:{port}{path}"


# --- module helpers (private) ---------------------------------------

def _api_key_env(ctx: OrchestrationContext) -> str:
    return (
        ctx.config.get("api_key_env")
        or f"{ctx.service_id.upper()}_API_KEY"
    ).strip()


def _config_path(ctx: OrchestrationContext) -> Path | None:
    rel = ctx.config.get("api_key_config")
    if not rel:
        return None
    config_root = (
        ctx.config.get("config_root")
        or ctx.extra.get("config_root")
        or os.environ.get("CONFIG_ROOT")
        or ""
    )
    return Path(config_root) / rel if config_root else Path(rel)


def _classify_source(ctx: OrchestrationContext, key: str) -> str:
    env_var = _api_key_env(ctx)
    if (ctx.secrets.get(env_var) or "").strip() == key:
        return "secrets"
    if os.environ.get(env_var, "").strip() == key:
        return "env"
    return "config_file"


# Type-check at import time. A constructor crash would surface here
# rather than at the first orchestrator call.
_check: ServiceLifecycle = ServarrLifecycle("sonarr")
del _check


__all__ = ["ServarrLifecycle"]
