apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../hardening.yaml
  - ../../secrets.example.yaml
  - ../../storage-pvc.yaml
  - ../../core.yaml
  - ../../optional.yaml
  - ../../envoy.yaml
  - ../../bootstrap.yaml
  - ../../ingress-traefik.yaml
  - ../../unpackerr.yaml
  - ../../scale-policy.yaml
