apiVersion: v1
kind: LimitRange
metadata:
  name: media-stack-default-limits
  namespace: media-stack
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: "2"
        memory: 2Gi
      max:
        cpu: "6"
        memory: 8Gi
