apiVersion: v1
kind: Secret
metadata:
  name: media-stack-secrets
  namespace: media-stack
type: Opaque
stringData:
  STACK_ADMIN_USERNAME: "admin"
  STACK_ADMIN_PASSWORD: "media-stack-admin"
  SABNZBD_API_KEY: ""
  JELLYFIN_API_KEY: ""
  JELLYFIN_USER_ID: ""
  JELLYSEERR_API_KEY: ""
  TAUTULLI_API_KEY: ""
  SONARR_API_KEY: ""
  RADARR_API_KEY: ""
  LIDARR_API_KEY: ""
  READARR_API_KEY: ""
  PROWLARR_API_KEY: ""
  UNPACKERR_SONARR_API_KEY: "replace-after-first-boot"
  UNPACKERR_RADARR_API_KEY: "replace-after-first-boot"
  UNPACKERR_LIDARR_API_KEY: "replace-after-first-boot"
  UNPACKERR_READARR_API_KEY: "replace-after-first-boot"
