"""Drift reconciliation between controller DB and providers.

An "orphan" is a user that exists in a provider but not in the controller
store — e.g. the admin user generated by the ``configure-auth`` bootstrap
job, or a user auto-provisioned by OIDC first-login in Jellyseerr.

A "ghost" is a controller-store user whose ``provider_refs`` point at an
external_id the provider no longer knows about — typically a user that
was deleted out-of-band.

Reconcile flow:
  1. List external users in every provider.
  2. Diff against controller store's provider_refs.
  3. Expose orphans/ghosts to the UI; admin picks a role and imports.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

_log = logging.getLogger("media_stack")

from media_stack.core.auth.users.audit_log import AuditLog
from media_stack.core.auth.users.models import UserState
from media_stack.core.auth.users.provider import UserProvider
from media_stack.core.auth.users.user_store import UserStore


@dataclass
class ProviderDiff:
    provider: str
    matched: int = 0
    orphans: list[dict[str, Any]] = field(default_factory=list)
    ghosts: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "provider": self.provider,
            "matched": self.matched,
            "orphans": list(self.orphans),
            "ghosts": list(self.ghosts),
        }


class ReconcileError(RuntimeError):
    pass


class UserReconciler:
    """Diffs controller store against provider user lists."""

    def __init__(
        self,
        *,
        store: UserStore,
        providers: list[UserProvider],
        audit: AuditLog,
    ) -> None:
        self._store = store
        self._providers = list(providers)
        self._audit = audit

    def diff(self) -> list[ProviderDiff]:
        """Return per-provider diff report."""
        live_users = [u for u in self._store.list_all(include_deleted=False)]
        diffs: list[ProviderDiff] = []
        for provider in self._providers:
            diffs.append(self._diff_provider(provider, live_users))
        return diffs

    def _diff_provider(self, provider: UserProvider, live_users: list) -> ProviderDiff:
        diff = ProviderDiff(provider=provider.name)
        try:
            remote = provider.list_users()
        except Exception as exc:  # noqa: BLE001
            diff.orphans = []
            diff.ghosts = [{"error": str(exc)[:99]}]
            return diff
        local_refs = {
            u.provider_refs.get(provider.name, ""): u
            for u in live_users
            if u.provider_refs.get(provider.name)
        }
        remote_ids = {ext.external_id for ext in remote}

        for ext in remote:
            if ext.external_id in local_refs:
                diff.matched += 1
            else:
                diff.orphans.append({
                    "external_id": ext.external_id,
                    "username": ext.username,
                    "email": ext.email,
                    "groups": list(ext.groups),
                })
        for ref, user in local_refs.items():
            if ref not in remote_ids:
                diff.ghosts.append({
                    "user_id": user.id,
                    "email": user.email,
                    "external_id": ref,
                })
        return diff

    def import_orphan(
        self,
        *,
        provider_name: str,
        external_id: str,
        role_slug: str,
        actor: str = "system",
        link_siblings_by_email: bool = True,
    ) -> dict[str, Any]:
        """Create controller row for an orphaned external user."""
        external, provider = self._resolve_orphan(provider_name, external_id)
        user, action = self._upsert_controller_row(
            provider_name, external_id, external, role_slug,
        )
        sibling_refs = self._link_siblings_if_requested(
            provider_name, external, user.id, link_siblings_by_email,
        )
        self._audit.append(
            actor=actor, action=action, target=user.email, result="ok",
            detail={
                "user_id": user.id, "provider": provider_name,
                "external_id": external_id, "role": role_slug,
                "linked_siblings": list(sibling_refs.keys()),
            },
        )
        refreshed = self._store.get(user.id)
        return refreshed.to_dict() if refreshed else user.to_dict()

    def _resolve_orphan(self, provider_name: str, external_id: str):
        provider = self._find_provider(provider_name)
        if provider is None:
            raise ReconcileError(f"unknown provider: {provider_name}")
        external = self._find_external(provider, external_id)
        if external is None:
            raise ReconcileError(
                f"user {external_id!r} not found in provider {provider_name}"
            )
        return external, provider

    def _upsert_controller_row(
        self, provider_name: str, external_id: str, external, role_slug: str,
    ):
        email = external.email or ""
        username = external.username or external_id
        display_name = str(external.extra.get("displayname")
                           or external.extra.get("display_name") or username)
        existing = (self._store.get_by_email(email) if email else None) \
            or self._store.get_by_username(username)
        if existing and existing.state != UserState.DELETED:
            user = self._store.update(
                existing.id, role_slug=role_slug,
                provider_refs={provider_name: external_id},
            )
            return user, "relink_orphan"
        user = self._store.create(
            email=email or f"{username}@unknown",
            username=username, display_name=display_name,
            role_slug=role_slug, state=UserState.ACTIVE,
        )
        self._store.update(user.id, provider_refs={provider_name: external_id})
        return user, "import_orphan"

    def _link_siblings_if_requested(
        self, provider_name: str, external, user_id: str, requested: bool,
    ) -> dict[str, str]:
        if not requested:
            return {}
        sibling_refs = self._find_sibling_refs(
            provider_name, external.username or "", external.email or "",
        )
        if sibling_refs:
            self._store.update(user_id, provider_refs=sibling_refs)
        return sibling_refs

    def _find_provider(self, name: str) -> UserProvider | None:
        for p in self._providers:
            if p.name == name:
                return p
        return None

    def _find_external(self, provider: UserProvider, external_id: str):
        try:
            for ext in provider.list_users():
                if ext.external_id == external_id:
                    return ext
        except Exception as exc:  # noqa: BLE001
            _log.debug("[DEBUG] reconcile lookup failed: %s", exc)
            return None
        return None

    def _find_sibling_refs(
        self, source_name: str, username: str, email: str,
    ) -> dict[str, str]:
        matches: dict[str, str] = {}
        for provider in self._providers:
            if provider.name == source_name:
                continue
            try:
                remote = provider.list_users()
            except Exception as exc:  # noqa: BLE001
                _log.debug("[DEBUG] sibling scan failed for %s: %s",
                           provider.name, exc)
                continue
            chosen = self._match_external(remote, username, email)
            if chosen is not None:
                matches[provider.name] = chosen.external_id
        return matches

    def _match_external(self, remote: list, username: str, email: str):
        target_username = (username or "").strip().lower()
        target_email = (email or "").strip().lower()
        for ext in remote:
            if target_username and ext.username.strip().lower() == target_username:
                return ext
            if target_email and ext.email.strip().lower() == target_email:
                return ext
        return None

    def unlink_ghost(
        self,
        *,
        user_id: str,
        provider_name: str,
        actor: str = "system",
    ) -> dict[str, Any]:
        """Drop a stale provider_ref on a controller user."""
        user = self._store.get(user_id)
        if not user:
            raise ReconcileError(f"user not found: {user_id}")
        if provider_name not in user.provider_refs:
            raise ReconcileError(
                f"user has no ref for provider: {provider_name}"
            )
        refs = dict(user.provider_refs)
        del refs[provider_name]
        # update() merges, so we need to set the full dict via a direct write
        self._store.update(user_id, provider_refs=None)
        for name, ref in refs.items():
            self._store.update(user_id, provider_refs={name: ref})
        self._audit.append(
            actor=actor, action="unlink_ghost", target=user.email, result="ok",
            detail={"user_id": user_id, "provider": provider_name},
        )
        return self._store.get(user_id).to_dict()
