apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespace.yaml
  - ../base/hardening.yaml
  - ../base/secrets.example.yaml
  - ../base/storage/storage-pvc.yaml
  - ../base/apps/core.yaml
  - ../base/apps/optional.yaml
  - ../base/ui/ui.yaml
  - ../base/edge/ingress-traefik.yaml
  - ../base/apps/unpackerr.yaml
  - ../base/scale-policy.yaml

images:
  - name: harbor.iomio.io/library/media-stack-controller
    newName: harbor.iomio.io/library/media-stack-controller
    newTag: v1.0.366
