// Stub for `virtual:pwa-register` used by vitest. The real virtual
// module is generated by vite-plugin-pwa at build time. Tests that
// need to assert on the SW registration override this with their own
// `vi.mock("virtual:pwa-register", ...)` call.

export interface RegisterSWOptions {
  immediate?: boolean;
  onNeedRefresh?: () => void;
  onOfflineReady?: () => void;
  onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
  onRegisterError?: (error: unknown) => void;
}

export function registerSW(_options?: RegisterSWOptions): (reload?: boolean) => Promise<void> {
  return async () => {};
}
