"""Unpackerr post-bootstrap: write config with discovered API keys.

Unpackerr needs Sonarr/Radarr/Lidarr/Readarr API keys. These keys only
exist after apps first boot. The bootstrap runner discovers them from
app config files, then writes an Unpackerr config file and restarts it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


class UnpackerrPreflightService:
    """Wraps Unpackerr config generation and restart logic."""

    def write_config_and_restart(
        self,
        *,
        config_root: str = "/srv-config",
        container_name: str = "unpackerr",
        log: Any = None,
        **kwargs: Any,
    ) -> None:
        """Write Unpackerr config with discovered API keys and restart."""

        def info(msg: str) -> None:
            if log:
                log(msg)

        import xml.etree.ElementTree as ET

        def _read_xml_api_key(config_path: Path) -> str:
            if not config_path.is_file():
                return ""
            try:
                tree = ET.parse(config_path)
                el = tree.find(".//ApiKey")
                return (el.text or "").strip() if el is not None else ""
            except Exception:
                return ""

        root = Path(config_root)
        sonarr_key = _read_xml_api_key(root / "sonarr" / "config.xml")
        radarr_key = _read_xml_api_key(root / "radarr" / "config.xml")
        lidarr_key = _read_xml_api_key(root / "lidarr" / "config.xml")
        readarr_key = _read_xml_api_key(root / "readarr" / "config.xml")

        keys_found = sum(1 for k in [sonarr_key, radarr_key, lidarr_key, readarr_key] if k)
        if keys_found == 0:
            info("Unpackerr: no API keys discovered, skipping config write")
            return

        # Write Unpackerr TOML config to the shared config mount.
        unpackerr_dir = root / "unpackerr"
        unpackerr_dir.mkdir(parents=True, exist_ok=True)
        conf_path = unpackerr_dir / "unpackerr.conf"

        lines = ["# Auto-generated by bootstrap runner. Do not edit manually.", ""]

        if sonarr_key:
            lines.extend([
                "[[sonarr]]",
                '  url = "http://sonarr:8989"',
                f'  api_key = "{sonarr_key}"',
                '  paths = ["/data/torrents/completed/tv", "/data/usenet/completed/tv"]',
                "",
            ])

        if radarr_key:
            lines.extend([
                "[[radarr]]",
                '  url = "http://radarr:7878"',
                f'  api_key = "{radarr_key}"',
                '  paths = ["/data/torrents/completed/movies", "/data/usenet/completed/movies"]',
                "",
            ])

        if lidarr_key:
            lines.extend([
                "[[lidarr]]",
                '  url = "http://lidarr:8686"',
                f'  api_key = "{lidarr_key}"',
                '  paths = ["/data/torrents/completed/music", "/data/usenet/completed/music"]',
                "",
            ])

        if readarr_key:
            lines.extend([
                "[[readarr]]",
                '  url = "http://readarr:8787"',
                f'  api_key = "{readarr_key}"',
                '  paths = ["/data/torrents/completed/books", "/data/usenet/completed/books"]',
                "",
            ])

        conf_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        info(f"Unpackerr: wrote config with {keys_found} API keys to {conf_path}")

        # Restart Unpackerr — Docker SDK (compose) or K8s pod delete.
        restarted = False
        try:
            import docker

            client = docker.from_env()
            container = client.containers.get(container_name)
            container.restart(timeout=15)
            restarted = True
        except Exception as exc:
            import logging; logging.getLogger("media_stack").debug("[DEBUG] Swallowed: %s", exc)
            pass
        if not restarted:
            try:
                from kubernetes import client as k8s_client, config as k8s_config

                try:
                    k8s_config.load_incluster_config()
                except k8s_config.ConfigException:
                    k8s_config.load_kube_config()
                v1 = k8s_client.CoreV1Api()
                namespace = __import__("os").environ.get("K8S_NAMESPACE", "media-stack")
                pods = v1.list_namespaced_pod(
                    namespace=namespace, label_selector=f"app={container_name}"
                )
                for pod in pods.items:
                    v1.delete_namespaced_pod(name=pod.metadata.name, namespace=namespace)
                restarted = True
            except Exception as exc:
                import logging; logging.getLogger("media_stack").debug("[DEBUG] Swallowed: %s", exc)
                pass
        if restarted:
            info(f"Unpackerr: restarted {container_name}")
        else:
            info(f"Unpackerr: restart skipped (no Docker or K8s access)")


_instance = UnpackerrPreflightService()
write_config_and_restart = _instance.write_config_and_restart
