"""Typed config models for bootstrap sections.

This module is kept as the stable import surface while model implementations
live in focused modules by domain.
"""

from __future__ import annotations

from .apps.jellyfin.config_models import (
    JellyfinArtworkHealthCheckConfig,
    JellyfinBookSidecarArtworkConfig,
    JellyfinLibrariesConfig,
    JellyfinLiveTvConfig,
    JellyfinLiveTvGuideConfig,
    JellyfinLiveTvTunerConfig,
    JellyfinMetadataBackfillConfig,
    JellyfinMusicSidecarArtworkConfig,
    JellyfinPlaybackConfig,
    JellyfinPluginsConfig,
    JellyfinPrewarmConfig,
)
from .config_models_discovery import (
    DiscoveryListContract,
    DiscoveryProviderOptions,
    GenericDiscoveryProviderOptions,
    GoodreadsListImportOptions,
    LastFmTagOptions,
    TmdbPopularImportOptions,
    TraktPopularImportOptions,
    parse_discovery_provider_options,
    resolve_discovery_list_contract,
)
from .config_models_download import (
    DiskGuardrailsConfig,
    DownloadClientConfig,
    DownloadClientsConfig,
    QbitAuthBypassConfig,
    QbitQueueGuardrailsConfig,
    QbitSeedingPolicyConfig,
    TechnologyBindingsConfig,
)
from .config_models_integrations import (
    AppAuthConfig,
    BazarrConfig,
    BoolSectionConfig,
    HomepageConfig,
    JellyfinAutoCollectionsConfig,
    JellyfinHomeRailsConfig,
    JellyseerrConfig,
    MaintainerrConfig,
    MaintainerrIntegrationsConfig,
    MediaHygieneConfig,
)
from .config_models_servarr import (
    AppCapabilities,
    ArrDiscoveryListEntry,
    ArrDiscoveryListsConfig,
    ArrDownloadHandlingOverride,
    ArrDownloadHandlingPolicy,
    ArrDownloadHandlingResolvedPolicy,
    ArrMediaManagementOverride,
    ArrMediaManagementPolicy,
    ArrMediaManagementResolvedPolicy,
    ArrQualityUpgradeOverride,
    ArrQualityUpgradePolicy,
    ArrQualityUpgradeResolvedPolicy,
    ServarrAppConfig,
)

__all__ = [
    "QbitQueueGuardrailsConfig",
    "QbitAuthBypassConfig",
    "QbitSeedingPolicyConfig",
    "DiskGuardrailsConfig",
    "DownloadClientConfig",
    "DownloadClientsConfig",
    "TechnologyBindingsConfig",
    "DiscoveryListContract",
    "DiscoveryProviderOptions",
    "GenericDiscoveryProviderOptions",
    "TmdbPopularImportOptions",
    "LastFmTagOptions",
    "GoodreadsListImportOptions",
    "TraktPopularImportOptions",
    "resolve_discovery_list_contract",
    "parse_discovery_provider_options",
    "BoolSectionConfig",
    "AppAuthConfig",
    "HomepageConfig",
    "BazarrConfig",
    "JellyfinHomeRailsConfig",
    "JellyfinAutoCollectionsConfig",
    "MediaHygieneConfig",
    "JellyseerrConfig",
    "MaintainerrConfig",
    "MaintainerrIntegrationsConfig",
    "JellyfinLiveTvTunerConfig",
    "JellyfinLiveTvGuideConfig",
    "JellyfinLiveTvConfig",
    "ArrDiscoveryListEntry",
    "ArrDiscoveryListsConfig",
    "ArrMediaManagementOverride",
    "ArrMediaManagementResolvedPolicy",
    "ArrMediaManagementPolicy",
    "ArrDownloadHandlingOverride",
    "ArrDownloadHandlingResolvedPolicy",
    "ArrDownloadHandlingPolicy",
    "ArrQualityUpgradeOverride",
    "ArrQualityUpgradeResolvedPolicy",
    "ArrQualityUpgradePolicy",
    "JellyfinLibrariesConfig",
    "JellyfinPluginsConfig",
    "JellyfinPlaybackConfig",
    "JellyfinBookSidecarArtworkConfig",
    "JellyfinMusicSidecarArtworkConfig",
    "JellyfinMetadataBackfillConfig",
    "JellyfinArtworkHealthCheckConfig",
    "JellyfinPrewarmConfig",
    "AppCapabilities",
    "ServarrAppConfig",
]
