#!/usr/bin/env bash

# Shared source-of-truth for files bundled into media-stack-bootstrap-script ConfigMap.
# Format: "<configmap-key>|<path-relative-to-repo-root>"
BOOTSTRAP_SCRIPT_CONFIGMAP_FILES=(
  "bootstrap_apps.py|scripts/bootstrap-apps.py"
  "bootstrap_lib__init__.py|scripts/bootstrap_lib/__init__.py"
  "bootstrap_lib__common.py|scripts/bootstrap_lib/common.py"
  "bootstrap_lib__http_client.py|scripts/bootstrap_lib/http_client.py"
  "bootstrap_lib__servarr.py|scripts/bootstrap_lib/servarr.py"
  "bootstrap_lib__homepage.py|scripts/bootstrap_lib/homepage.py"
  "bootstrap_lib__bazarr.py|scripts/bootstrap_lib/bazarr.py"
  "bootstrap_lib__jellyfin.py|scripts/bootstrap_lib/jellyfin.py"
  "bootstrap_lib__defaults.py|scripts/bootstrap_lib/defaults.py"
  "bootstrap_defaults__maintainerr_policy.json|scripts/bootstrap_defaults/maintainerr_policy.json"
  "bootstrap_defaults__jellyfin_home_rails.json|scripts/bootstrap_defaults/jellyfin_home_rails.json"
  "bootstrap_defaults__adapter_hooks.json|scripts/bootstrap_defaults/adapter_hooks.json"
  "bootstrap_defaults__app_capability_defaults.json|scripts/bootstrap_defaults/app_capability_defaults.json"
  "bootstrap_defaults__media_server_operation_plans.json|scripts/bootstrap_defaults/media_server_operation_plans.json"
  "bootstrap_services__init__.py|scripts/bootstrap_services/__init__.py"
  "bootstrap_services__arr_service.py|scripts/bootstrap_services/arr_service.py"
  "bootstrap_services__arr_queue_cleanup_service.py|scripts/bootstrap_services/arr_queue_cleanup_service.py"
  "bootstrap_services__adapter_reflection.py|scripts/bootstrap_services/adapter_reflection.py"
  "bootstrap_services__api_keys_service.py|scripts/bootstrap_services/api_keys_service.py"
  "bootstrap_services__auth_service.py|scripts/bootstrap_services/auth_service.py"
  "bootstrap_services__bootstrap_runner_service.py|scripts/bootstrap_services/bootstrap_runner_service.py"
  "bootstrap_services__download_client_pipeline_service.py|scripts/bootstrap_services/download_client_pipeline_service.py"
  "bootstrap_services__download_client_adapters__init__.py|scripts/bootstrap_services/download_client_adapters/__init__.py"
  "bootstrap_services__download_client_adapters__base.py|scripts/bootstrap_services/download_client_adapters/base.py"
  "bootstrap_services__download_client_adapters__factory.py|scripts/bootstrap_services/download_client_adapters/factory.py"
  "bootstrap_services__download_client_adapters__generic.py|scripts/bootstrap_services/download_client_adapters/generic.py"
  "bootstrap_services__download_client_adapters__qbittorrent.py|scripts/bootstrap_services/download_client_adapters/qbittorrent.py"
  "bootstrap_services__download_client_adapters__sabnzbd.py|scripts/bootstrap_services/download_client_adapters/sabnzbd.py"
  "bootstrap_services__download_client_adapters__transmission.py|scripts/bootstrap_services/download_client_adapters/transmission.py"
  "bootstrap_services__media_server_adapters__init__.py|scripts/bootstrap_services/media_server_adapters/__init__.py"
  "bootstrap_services__media_server_adapters__base.py|scripts/bootstrap_services/media_server_adapters/base.py"
  "bootstrap_services__media_server_adapters__factory.py|scripts/bootstrap_services/media_server_adapters/factory.py"
  "bootstrap_services__media_server_adapters__generic.py|scripts/bootstrap_services/media_server_adapters/generic.py"
  "bootstrap_services__media_server_adapters__jellyfin.py|scripts/bootstrap_services/media_server_adapters/jellyfin.py"
  "bootstrap_services__media_server_adapters__plans.py|scripts/bootstrap_services/media_server_adapters/plans.py"
  "bootstrap_services__entrypoint_runtime.py|scripts/bootstrap_services/entrypoint_runtime.py"
  "bootstrap_services__runtime_core.py|scripts/bootstrap_services/runtime_core.py"
  "bootstrap_services__runtime_media_ops.py|scripts/bootstrap_services/runtime_media_ops.py"
  "bootstrap_services__runtime_servarr_ops.py|scripts/bootstrap_services/runtime_servarr_ops.py"
  "bootstrap_services__apps__init__.py|scripts/bootstrap_services/apps/__init__.py"
  "bootstrap_services__apps__bazarr__init__.py|scripts/bootstrap_services/apps/bazarr/__init__.py"
  "bootstrap_services__apps__bazarr__service.py|scripts/bootstrap_services/apps/bazarr/service.py"
  "bootstrap_services__apps__jellyfin__init__.py|scripts/bootstrap_services/apps/jellyfin/__init__.py"
  "bootstrap_services__apps__jellyfin__home_rails_service.py|scripts/bootstrap_services/apps/jellyfin/home_rails_service.py"
  "bootstrap_services__apps__jellyfin__libraries_service.py|scripts/bootstrap_services/apps/jellyfin/libraries_service.py"
  "bootstrap_services__apps__jellyfin__livetv_service.py|scripts/bootstrap_services/apps/jellyfin/livetv_service.py"
  "bootstrap_services__apps__jellyfin__livetv_source_service.py|scripts/bootstrap_services/apps/jellyfin/livetv_source_service.py"
  "bootstrap_services__apps__jellyfin__livetv_state_service.py|scripts/bootstrap_services/apps/jellyfin/livetv_state_service.py"
  "bootstrap_services__apps__jellyfin__playback_service.py|scripts/bootstrap_services/apps/jellyfin/playback_service.py"
  "bootstrap_services__apps__jellyfin__plugins_service.py|scripts/bootstrap_services/apps/jellyfin/plugins_service.py"
  "bootstrap_services__apps__jellyfin__prewarm_service.py|scripts/bootstrap_services/apps/jellyfin/prewarm_service.py"
  "bootstrap_services__apps__jellyseerr__init__.py|scripts/bootstrap_services/apps/jellyseerr/__init__.py"
  "bootstrap_services__apps__jellyseerr__service.py|scripts/bootstrap_services/apps/jellyseerr/service.py"
  "bootstrap_services__apps__prowlarr__init__.py|scripts/bootstrap_services/apps/prowlarr/__init__.py"
  "bootstrap_services__apps__prowlarr__service.py|scripts/bootstrap_services/apps/prowlarr/service.py"
  "bootstrap_services__apps__qbittorrent__init__.py|scripts/bootstrap_services/apps/qbittorrent/__init__.py"
  "bootstrap_services__apps__qbittorrent__service.py|scripts/bootstrap_services/apps/qbittorrent/service.py"
  "bootstrap_services__apps__sabnzbd__init__.py|scripts/bootstrap_services/apps/sabnzbd/__init__.py"
  "bootstrap_services__apps__sabnzbd__service.py|scripts/bootstrap_services/apps/sabnzbd/service.py"
  "bootstrap_services__apps__tautulli__init__.py|scripts/bootstrap_services/apps/tautulli/__init__.py"
  "bootstrap_services__apps__tautulli__service.py|scripts/bootstrap_services/apps/tautulli/service.py"
  "bootstrap_services__runtime_factory_service.py|scripts/bootstrap_services/runtime_factory_service.py"
  "bootstrap_services__operation_wiring.py|scripts/bootstrap_services/operation_wiring.py"
  "bootstrap_services__runtime_helpers.py|scripts/bootstrap_services/runtime_helpers.py"
  "bootstrap_services__runner_operations_service.py|scripts/bootstrap_services/runner_operations_service.py"
  "bootstrap_services__config_models.py|scripts/bootstrap_services/config_models.py"
  "bootstrap_services__disk_guardrails_service.py|scripts/bootstrap_services/disk_guardrails_service.py"
  "bootstrap_services__discovery_lists_service.py|scripts/bootstrap_services/discovery_lists_service.py"
  "bootstrap_services__enums.py|scripts/bootstrap_services/enums.py"
  "bootstrap_services__health_service.py|scripts/bootstrap_services/health_service.py"
  "bootstrap_services__bazarr_service.py|scripts/bootstrap_services/bazarr_service.py"
  "bootstrap_services__jellyfin_service.py|scripts/bootstrap_services/jellyfin_service.py"
  "bootstrap_services__jellyfin_livetv_source_service.py|scripts/bootstrap_services/jellyfin_livetv_source_service.py"
  "bootstrap_services__jellyfin_livetv_state_service.py|scripts/bootstrap_services/jellyfin_livetv_state_service.py"
  "bootstrap_services__jellyfin_libraries_service.py|scripts/bootstrap_services/jellyfin_libraries_service.py"
  "bootstrap_services__jellyfin_home_rails_service.py|scripts/bootstrap_services/jellyfin_home_rails_service.py"
  "bootstrap_services__jellyfin_playback_service.py|scripts/bootstrap_services/jellyfin_playback_service.py"
  "bootstrap_services__jellyfin_plugins_service.py|scripts/bootstrap_services/jellyfin_plugins_service.py"
  "bootstrap_services__jellyfin_prewarm_service.py|scripts/bootstrap_services/jellyfin_prewarm_service.py"
  "bootstrap_services__jellyseerr_service.py|scripts/bootstrap_services/jellyseerr_service.py"
  "bootstrap_services__media_hygiene_ops_service.py|scripts/bootstrap_services/media_hygiene_ops_service.py"
  "bootstrap_services__media_hygiene_service.py|scripts/bootstrap_services/media_hygiene_service.py"
  "bootstrap_services__prowlarr_service.py|scripts/bootstrap_services/prowlarr_service.py"
  "bootstrap_services__qbit_service.py|scripts/bootstrap_services/qbit_service.py"
  "bootstrap_services__sabnzbd_service.py|scripts/bootstrap_services/sabnzbd_service.py"
  "bootstrap_services__servarr_adapters.py|scripts/bootstrap_services/servarr_adapters.py"
  "bootstrap_services__servarr_technology_adapters.py|scripts/bootstrap_services/servarr_technology_adapters.py"
  "bootstrap_services__servarr_technologies__init__.py|scripts/bootstrap_services/servarr_technologies/__init__.py"
  "bootstrap_services__servarr_technologies__base.py|scripts/bootstrap_services/servarr_technologies/base.py"
  "bootstrap_services__servarr_technologies__factory.py|scripts/bootstrap_services/servarr_technologies/factory.py"
  "bootstrap_services__servarr_technologies__generic.py|scripts/bootstrap_services/servarr_technologies/generic.py"
  "bootstrap_services__servarr_technologies__sonarr.py|scripts/bootstrap_services/servarr_technologies/sonarr.py"
  "bootstrap_services__servarr_technologies__radarr.py|scripts/bootstrap_services/servarr_technologies/radarr.py"
  "bootstrap_services__servarr_technologies__lidarr.py|scripts/bootstrap_services/servarr_technologies/lidarr.py"
  "bootstrap_services__servarr_technologies__readarr.py|scripts/bootstrap_services/servarr_technologies/readarr.py"
  "bootstrap_services__servarr_types.py|scripts/bootstrap_services/servarr_types.py"
  "bootstrap_services__technology_catalog.py|scripts/bootstrap_services/technology_catalog.py"
  "bootstrap_services__technology_lifecycle_service.py|scripts/bootstrap_services/technology_lifecycle_service.py"
  "bootstrap_services__servarr_policy_service.py|scripts/bootstrap_services/servarr_policy_service.py"
  "bootstrap_services__servarr_pipeline_service.py|scripts/bootstrap_services/servarr_pipeline_service.py"
  "bootstrap_services__config_artifacts_service.py|scripts/bootstrap_services/config_artifacts_service.py"
  "core__init__.py|scripts/core/__init__.py"
  "core__decorators.py|scripts/core/decorators.py"
  "core__http.py|scripts/core/http.py"
)

bootstrap_script_configmap_create_yaml() {
  local namespace="$1"
  local root_dir="$2"
  local output_file="$3"
  local entry key rel
  local -a args=()

  for entry in "${BOOTSTRAP_SCRIPT_CONFIGMAP_FILES[@]}"; do
    IFS='|' read -r key rel <<<"$entry"
    args+=(--from-file="${key}=${root_dir}/${rel}")
  done

  "${KUBECTL[@]}" -n "$namespace" create configmap media-stack-bootstrap-script \
    "${args[@]}" \
    --dry-run=client -o yaml >"$output_file"
}
