"""Unpackerr post-bootstrap: write config with discovered API keys.

Unpackerr needs Sonarr/Radarr/Lidarr/Readarr API keys. These keys only
exist after apps first boot. The bootstrap runner discovers them from
app config files, then writes an Unpackerr config file and restarts it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def write_config_and_restart(
    *,
    config_root: str = "/srv-config",
    container_name: str = "unpackerr",
    log: Any = None,
    **kwargs: Any,
) -> None:
    """Write Unpackerr config with discovered API keys and restart."""

    def info(msg: str) -> None:
        if log:
            log(msg)

    from bootstrap_api.preflight.api_keys import _read_xml_api_key

    root = Path(config_root)
    sonarr_key = _read_xml_api_key(root / "sonarr" / "config.xml")
    radarr_key = _read_xml_api_key(root / "radarr" / "config.xml")
    lidarr_key = _read_xml_api_key(root / "lidarr" / "config.xml")
    readarr_key = _read_xml_api_key(root / "readarr" / "config.xml")

    keys_found = sum(1 for k in [sonarr_key, radarr_key, lidarr_key, readarr_key] if k)
    if keys_found == 0:
        info("Unpackerr: no API keys discovered, skipping config write")
        return

    # Write Unpackerr TOML config to the shared config mount.
    unpackerr_dir = root / "unpackerr"
    unpackerr_dir.mkdir(parents=True, exist_ok=True)
    conf_path = unpackerr_dir / "unpackerr.conf"

    lines = ["# Auto-generated by bootstrap runner. Do not edit manually.", ""]

    if sonarr_key:
        lines.extend([
            "[[sonarr]]",
            '  url = "http://sonarr:8989"',
            f'  api_key = "{sonarr_key}"',
            '  paths = ["/data/torrents/completed/tv", "/data/usenet/completed/tv"]',
            "",
        ])

    if radarr_key:
        lines.extend([
            "[[radarr]]",
            '  url = "http://radarr:7878"',
            f'  api_key = "{radarr_key}"',
            '  paths = ["/data/torrents/completed/movies", "/data/usenet/completed/movies"]',
            "",
        ])

    if lidarr_key:
        lines.extend([
            "[[lidarr]]",
            '  url = "http://lidarr:8686"',
            f'  api_key = "{lidarr_key}"',
            '  paths = ["/data/torrents/completed/music", "/data/usenet/completed/music"]',
            "",
        ])

    if readarr_key:
        lines.extend([
            "[[readarr]]",
            '  url = "http://readarr:8787"',
            f'  api_key = "{readarr_key}"',
            '  paths = ["/data/torrents/completed/books", "/data/usenet/completed/books"]',
            "",
        ])

    conf_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    info(f"Unpackerr: wrote config with {keys_found} API keys to {conf_path}")

    # Restart Unpackerr to pick up the config file.
    try:
        import docker

        client = docker.from_env()
        container = client.containers.get(container_name)
        container.restart(timeout=15)
        info(f"Unpackerr: restarted {container_name}")
    except Exception as exc:
        info(f"Unpackerr: restart skipped ({exc})")
