"""Envoy ``ServiceLifecycle`` — ADR-0003 Phase 3c.

Envoy's admin endpoint exposes ``/ready`` for liveness; it has no
API key (config is generated by ``envoy-config-init``). Probe-only
service.
"""

from __future__ import annotations

from media_stack.adapters._lifecycle_base import NoApiKeyLifecycleBase
from media_stack.domain.services import ServiceLifecycle


class EnvoyLifecycle(NoApiKeyLifecycleBase):
    service_id = "envoy"
    _default_health_path = "/ready"


_check: ServiceLifecycle = EnvoyLifecycle()
del _check


__all__ = ["EnvoyLifecycle"]
