"""Generate docs/reference/promises.md from .ratchets/promises/promises.yaml.

Console-script: ``media-stack-render-promises`` (after ``pip install``).
Module path: ``python -m media_stack.cli.commands.render_promises_reference``.

The promises registry is the source of truth for "what works OTB after
a fresh install." This script renders a human-readable reference table
so the docs can't drift from the registry — re-run after editing
``.ratchets/promises/promises.yaml``.

One registry, one output. The earlier promises-k8s.yaml /
promises-k8s.md pair was folded into the main file in v1.0.169; every
promise now carries a ``platforms:`` field so the renderer groups them
by runtime without needing a second document.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# File now lives at src/media_stack/cli/commands/<this>.py — five
# levels under the repo root (was bin/<this>.py — one level when the
# old `parent.parent` calculation was correct).
REPO_ROOT = Path(__file__).resolve().parents[4]
PROMISES_YAML = REPO_ROOT / ".ratchets" / "promises" / "promises.yaml"
OUTPUT = REPO_ROOT / "docs" / "reference" / "promises.md"


def _probe_target(probe: dict) -> str:
    """Short human-readable description of what the probe hits."""
    ptype = str(probe.get("type") or "").strip()
    if ptype.startswith("http"):
        return f"`{ptype}` &rarr; {probe.get('service', '')}{probe.get('path', '')}"
    if ptype.startswith("file"):
        return f"`{ptype}` &rarr; {probe.get('path', '')}"
    if ptype == "k8s_resource":
        kind = str(probe.get("kind") or "").strip()
        ns = str(probe.get("namespace") or "").strip()
        sel = str(probe.get("label_selector") or "").strip()
        bits = [f"`{kind}`"]
        if ns:
            bits.append(f"in `{ns}`")
        if sel:
            bits.append(f"matching `{sel}`")
        return " ".join(bits)
    if ptype == "k8s_exec":
        pod = str(probe.get("pod_label") or "").strip()
        return f"`k8s_exec` &rarr; pod `{pod}`"
    return f"`{ptype}`"


def _platform_badge(platforms: list) -> str:
    """Compact per-platform tag rendered in the table."""
    if not platforms:
        return "&mdash;"
    if set(platforms) == {"compose", "k8s"}:
        return "compose + k8s"
    return " + ".join(sorted(platforms))


def render() -> str:
    data = yaml.safe_load(PROMISES_YAML.read_text(encoding="utf-8")) or {}
    promises = data.get("promises") or []

    by_platform = {
        "both": [p for p in promises if set(p.get("platforms") or []) == {"compose", "k8s"}],
        "compose": [p for p in promises if (p.get("platforms") or []) == ["compose"]],
        "k8s": [p for p in promises if (p.get("platforms") or []) == ["k8s"]],
    }

    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by media-stack-render-promises -->")
    lines.append("<!-- Source: .ratchets/promises/promises.yaml. Edit the YAML, then re-run the script. -->")
    lines.append("")
    lines.append("# Promises Reference")
    lines.append("")
    lines.append(
        "Every claim like \"after a fresh install, Bazarr has English subtitles enabled\" "
        "lives in [`.ratchets/promises/promises.yaml`](../../.ratchets/promises/promises.yaml) as a single "
        "declarative entry. Three things consume that file:"
    )
    lines.append("")
    lines.append("1. The meta-ratchet (`tests/unit/test_promises_registry.py`) — verifies every promise is well-formed, platform-tagged, and points at a real handler (compose) or the infrastructure vocab (k8s).")
    lines.append("2. The fresh-install verifier (`bin/verify-fresh-install.sh` and `media-stack-probe-promises [--k8s]`) — runs each probe against a live stack.")
    lines.append("3. This page — the human-readable index.")
    lines.append("")
    lines.append("## Platforms")
    lines.append("")
    lines.append(
        "Every promise declares which runtime(s) it applies to via the `platforms:` field:\n"
        "- **compose + k8s** — agnostic, probed on both runtimes.\n"
        "- **compose** — failure modes unique to the docker-compose stack.\n"
        "- **k8s** — PVC, image-pull, ingress, and other Kubernetes-only failure modes."
    )
    lines.append("")
    lines.append(
        f"There are **{len(promises)} promises** at this commit — "
        f"{len(by_platform['both'])} agnostic, "
        f"{len(by_platform['compose'])} compose-only, "
        f"{len(by_platform['k8s'])} k8s-only."
    )
    lines.append("")
    lines.append("## How to read the tables")
    lines.append("")
    lines.append(
        "- **Promise** — the claim. After a clean bootstrap, the promise should hold and stay holding.\n"
        "- **Ensured by** — the contract job whose handler makes the promise true "
        "(compose vocabulary) or the infra layer that guarantees it (`kubectl-apply` / `operator` for k8s-only promises).\n"
        "- **Probe** — what the verifier checks to prove the promise actually holds in a live stack."
    )
    lines.append("")

    def _section(title: str, items: list, intro: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(intro)
        lines.append("")
        if not items:
            lines.append("_none_")
            lines.append("")
            return
        lines.append("| Promise | Ensured by | Probe |")
        lines.append("|---|---|---|")
        for p in items:
            pid = str(p.get("id") or "").strip()
            desc = str(p.get("description") or "").strip().replace("|", "\\|")
            ensured = str(p.get("ensured_by") or "").strip()
            target = _probe_target(p.get("probe") or {})
            lines.append(f"| **{pid}** &mdash; {desc} | `{ensured}` | {target} |")
        lines.append("")

    _section(
        "Agnostic promises (compose + k8s)",
        by_platform["both"],
        "Run on both runtimes. On k8s the HTTP/file probes are routed through "
        "`kubectl exec` into the controller pod so the same assertion exercises "
        "both stacks.",
    )
    _section(
        "Compose-only promises",
        by_platform["compose"],
        "Failure modes specific to the docker-compose stack — typically because "
        "the k8s ingress layer handles the same concern differently and has its "
        "own k8s-only probe.",
    )
    _section(
        "Kubernetes-only promises",
        by_platform["k8s"],
        "PVC phases, image-pull state, pod readiness, ingress rules, and other "
        "failure modes that have no compose equivalent. The `ensured_by` vocabulary "
        "here is infrastructure-layer (`kubectl-apply`, `operator`) rather than "
        "contract-job names.",
    )

    lines.append("## Running the probes")
    lines.append("")
    lines.append("```bash")
    lines.append("media-stack-probe-promises          # compose-side probes against localhost")
    lines.append("media-stack-probe-promises --k8s    # every applicable promise against the cluster")
    lines.append("media-stack-probe-promises --filter auth   # narrow by substring")
    lines.append("```")
    lines.append("")
    lines.append("The runner fails-fast on any promise that returns false. `skipped` entries are counted as pass (wrong platform, file-missing with `skip_if_missing: true`, etc.).")
    lines.append("")
    lines.append("## Adding a new promise")
    lines.append("")
    lines.append("1. Write the `ensure_*` adapter that re-asserts the desired state. Idempotent &mdash; every run leaves the system in the same end state.")
    lines.append("2. Register a contract job pointing at the adapter (`phase: post`).")
    lines.append("3. Add an entry to [`.ratchets/promises/promises.yaml`](../../.ratchets/promises/promises.yaml) with a probe that proves it works, and a `platforms:` tag.")
    lines.append("4. Re-run this script: `media-stack-render-promises`.")
    lines.append("")
    lines.append("If steps 1+2 happen but step 3 doesn't, the meta-ratchet warns (orphan adapter); if step 3 happens without 1+2, the meta-ratchet fails hard (broken promise).")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Project Steward**")
    lines.append("Matthew Loschiavo &middot; [matthewloschiavo.com](https://matthewloschiavo.com) &middot; [mploschiavo@gmail.com](mailto:mploschiavo@gmail.com) &middot; [LinkedIn](https://www.linkedin.com/in/matthewloschiavo)")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not PROMISES_YAML.is_file():
        print(f"ERROR: missing {PROMISES_YAML}", file=sys.stderr)
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
