#!/usr/bin/env bash
set -euo pipefail

NAMESPACE="${NAMESPACE:-media-stack}"
SECRET_NAME="${SECRET_NAME:-media-stack-secrets}"
OUTPUT_FILE="${OUTPUT_FILE:-./secrets.generated.env}"
ROTATE_EXISTING="${ROTATE_EXISTING:-0}"
PASS_LENGTH="${PASS_LENGTH:-24}"
STACK_ADMIN_USER="${STACK_ADMIN_USER:-admin}"

usage() {
  cat <<'EOF'
Usage:
  scripts/generate-secrets.sh

Description:
  Generates secure credentials and applies/updates the Kubernetes secret used by
  media-stack. Writes generated values to a local env file with mode 600.

Environment variables:
  NAMESPACE        (default: media-stack)
  SECRET_NAME      (default: media-stack-secrets)
  OUTPUT_FILE      (default: ./secrets.generated.env)
  ROTATE_EXISTING  (default: 0; set to 1 to rotate stack admin credentials)
  STACK_ADMIN_USER (default: admin)
  SABNZBD_API_KEY  (default: preserve existing or empty; optional bootstrap override)
  PASS_LENGTH      (default: 24)
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if command -v microk8s >/dev/null 2>&1; then
  KUBECTL=(microk8s kubectl)
elif command -v kubectl >/dev/null 2>&1; then
  KUBECTL=(kubectl)
else
  echo "[ERR] Neither microk8s nor kubectl is available in PATH." >&2
  exit 1
fi

rand_secret() {
  local n="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 64 | tr -dc 'A-Za-z0-9@#%+=:._-' | head -c "$n"
  else
    tr -dc 'A-Za-z0-9@#%+=:._-' </dev/urandom | head -c "$n"
  fi
}

get_secret_key() {
  local key="$1"
  "${KUBECTL[@]}" -n "$NAMESPACE" get secret "$SECRET_NAME" \
    -o "jsonpath={.data.$key}" 2>/dev/null | base64 -d 2>/dev/null || true
}

exists=0
if "${KUBECTL[@]}" -n "$NAMESPACE" get secret "$SECRET_NAME" >/dev/null 2>&1; then
  exists=1
fi

current_sab_api_key="$(get_secret_key SABNZBD_API_KEY)"
current_jellyfin_api_key="$(get_secret_key JELLYFIN_API_KEY)"
current_jellyfin_user_id="$(get_secret_key JELLYFIN_USER_ID)"
current_un_sonarr="$(get_secret_key UNPACKERR_SONARR_API_KEY)"
current_un_radarr="$(get_secret_key UNPACKERR_RADARR_API_KEY)"
current_un_lidarr="$(get_secret_key UNPACKERR_LIDARR_API_KEY)"
current_un_readarr="$(get_secret_key UNPACKERR_READARR_API_KEY)"
current_stack_admin_user="$(get_secret_key STACK_ADMIN_USERNAME)"
current_stack_admin_pass="$(get_secret_key STACK_ADMIN_PASSWORD)"

if [[ -z "$current_stack_admin_user" || "$ROTATE_EXISTING" == "1" ]]; then
  current_stack_admin_user="$STACK_ADMIN_USER"
fi
if [[ -z "$current_stack_admin_pass" || "$ROTATE_EXISTING" == "1" ]]; then
  current_stack_admin_pass="$(rand_secret "$PASS_LENGTH")"
fi
if [[ -z "$current_jellyfin_api_key" ]]; then
  current_jellyfin_api_key=""
fi
if [[ -z "$current_sab_api_key" ]]; then
  current_sab_api_key=""
fi
if [[ -z "$current_jellyfin_user_id" ]]; then
  current_jellyfin_user_id=""
fi
if [[ -z "$current_un_sonarr" ]]; then
  current_un_sonarr="replace-after-first-boot"
fi
if [[ -z "$current_un_radarr" ]]; then
  current_un_radarr="replace-after-first-boot"
fi
if [[ -z "$current_un_lidarr" ]]; then
  current_un_lidarr="replace-after-first-boot"
fi
if [[ -z "$current_un_readarr" ]]; then
  current_un_readarr="replace-after-first-boot"
fi

cat <<EOF | "${KUBECTL[@]}" apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  STACK_ADMIN_USERNAME: "${current_stack_admin_user}"
  STACK_ADMIN_PASSWORD: "${current_stack_admin_pass}"
  SABNZBD_API_KEY: "${current_sab_api_key}"
  JELLYFIN_API_KEY: "${current_jellyfin_api_key}"
  JELLYFIN_USER_ID: "${current_jellyfin_user_id}"
  UNPACKERR_SONARR_API_KEY: "${current_un_sonarr}"
  UNPACKERR_RADARR_API_KEY: "${current_un_radarr}"
  UNPACKERR_LIDARR_API_KEY: "${current_un_lidarr}"
  UNPACKERR_READARR_API_KEY: "${current_un_readarr}"
EOF

mkdir -p "$(dirname "$OUTPUT_FILE")"
cat >"$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-secrets.sh
# Keep this file private.
NAMESPACE=${NAMESPACE}
SECRET_NAME=${SECRET_NAME}
STACK_ADMIN_USERNAME=${current_stack_admin_user}
STACK_ADMIN_PASSWORD=${current_stack_admin_pass}
SABNZBD_API_KEY=${current_sab_api_key}
JELLYFIN_API_KEY=${current_jellyfin_api_key}
JELLYFIN_USER_ID=${current_jellyfin_user_id}
EOF
chmod 600 "$OUTPUT_FILE"

if [[ "$exists" == "1" ]]; then
  echo "[OK] Updated secret ${NAMESPACE}/${SECRET_NAME}"
else
  echo "[OK] Created secret ${NAMESPACE}/${SECRET_NAME}"
fi
echo "[OK] Wrote generated credentials to ${OUTPUT_FILE} (mode 600)"
