#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_IP="${1:-${STACK_NODE_IP:-}}"
NAMESPACE="${2:-${NAMESPACE:-media-stack}}"
OUT_DIR="${3:-${STACK_SCREENSHOT_DIR:-$ROOT_DIR/docs/screenshots/apps}}"
SECRET_NAME="${STACK_SECRET_NAME:-media-stack-secrets}"

if [[ -z "${NODE_IP}" ]]; then
  echo "[ERR] Missing NODE_IP. Usage: scripts/run-playwright-screenshots.sh <NODE_IP> [NAMESPACE] [OUT_DIR]" >&2
  exit 1
fi

HOSTS_LINE="$(bash "$ROOT_DIR/scripts/render-hosts-example.sh" "$NODE_IP" "$NAMESPACE")"
HOSTS_CSV="$(echo "$HOSTS_LINE" | cut -d' ' -f2- | tr ' ' ',')"

echo "[INFO] Capturing Playwright UI screenshots"
echo "[INFO] NODE_IP: $NODE_IP"
echo "[INFO] NAMESPACE: $NAMESPACE"
echo "[INFO] OUT_DIR: $OUT_DIR"
echo "[INFO] HOSTS: $HOSTS_CSV"

mkdir -p "$OUT_DIR"

secret_value() {
  local key="$1"
  kubectl -n "$NAMESPACE" get secret "$SECRET_NAME" -o "jsonpath={.data.${key}}" 2>/dev/null \
    | base64 -d 2>/dev/null || true
}

STACK_ADMIN_USERNAME_RESOLVED="${STACK_ADMIN_USERNAME:-$(secret_value STACK_ADMIN_USERNAME)}"
STACK_ADMIN_PASSWORD_RESOLVED="${STACK_ADMIN_PASSWORD:-$(secret_value STACK_ADMIN_PASSWORD)}"
JELLYSEERR_USERNAME_RESOLVED="${JELLYSEERR_USERNAME:-$STACK_ADMIN_USERNAME_RESOLVED}"
JELLYSEERR_PASSWORD_RESOLVED="${JELLYSEERR_PASSWORD:-$STACK_ADMIN_PASSWORD_RESOLVED}"
SABNZBD_USERNAME_RESOLVED="${SABNZBD_USERNAME:-$STACK_ADMIN_USERNAME_RESOLVED}"
SABNZBD_PASSWORD_RESOLVED="${SABNZBD_PASSWORD:-$STACK_ADMIN_PASSWORD_RESOLVED}"

if [[ -n "${STACK_ADMIN_USERNAME_RESOLVED}" ]]; then
  echo "[INFO] Screenshot auth user: ${STACK_ADMIN_USERNAME_RESOLVED}"
fi

pushd "$ROOT_DIR/tests/e2e/playwright" >/dev/null
if [[ ! -d node_modules ]]; then
  if ! npm ci; then
    npm install
  fi
fi

if ! STACK_NODE_IP="$NODE_IP" STACK_HOSTS="$HOSTS_CSV" STACK_SCREENSHOT_DIR="$OUT_DIR" \
  STACK_ADMIN_USERNAME="$STACK_ADMIN_USERNAME_RESOLVED" \
  STACK_ADMIN_PASSWORD="$STACK_ADMIN_PASSWORD_RESOLVED" \
  JELLYSEERR_USERNAME="$JELLYSEERR_USERNAME_RESOLVED" \
  JELLYSEERR_PASSWORD="$JELLYSEERR_PASSWORD_RESOLVED" \
  SABNZBD_USERNAME="$SABNZBD_USERNAME_RESOLVED" \
  SABNZBD_PASSWORD="$SABNZBD_PASSWORD_RESOLVED" \
  npx playwright test tests/screenshot-capture.spec.ts --reporter=list --workers=1; then
  STACK_NODE_IP="$NODE_IP" STACK_HOSTS="$HOSTS_CSV" STACK_SCREENSHOT_DIR="$OUT_DIR" \
    STACK_ADMIN_USERNAME="$STACK_ADMIN_USERNAME_RESOLVED" \
    STACK_ADMIN_PASSWORD="$STACK_ADMIN_PASSWORD_RESOLVED" \
    JELLYSEERR_USERNAME="$JELLYSEERR_USERNAME_RESOLVED" \
    JELLYSEERR_PASSWORD="$JELLYSEERR_PASSWORD_RESOLVED" \
    SABNZBD_USERNAME="$SABNZBD_USERNAME_RESOLVED" \
    SABNZBD_PASSWORD="$SABNZBD_PASSWORD_RESOLVED" \
    npx playwright install chromium >/dev/null 2>&1 || true
  STACK_NODE_IP="$NODE_IP" STACK_HOSTS="$HOSTS_CSV" STACK_SCREENSHOT_DIR="$OUT_DIR" \
    STACK_ADMIN_USERNAME="$STACK_ADMIN_USERNAME_RESOLVED" \
    STACK_ADMIN_PASSWORD="$STACK_ADMIN_PASSWORD_RESOLVED" \
    JELLYSEERR_USERNAME="$JELLYSEERR_USERNAME_RESOLVED" \
    JELLYSEERR_PASSWORD="$JELLYSEERR_PASSWORD_RESOLVED" \
    SABNZBD_USERNAME="$SABNZBD_USERNAME_RESOLVED" \
    SABNZBD_PASSWORD="$SABNZBD_PASSWORD_RESOLVED" \
    npx playwright test tests/screenshot-capture.spec.ts --reporter=list --workers=1
fi
popd >/dev/null

echo "[OK] Screenshot capture complete."
ls -1 "$OUT_DIR"/*.png 2>/dev/null || true
