apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../hardening.yaml
  - ../../secrets.example.yaml
  - ../../storage-pvc.yaml
  - ../../core.yaml
  - ../../optional.yaml
  - ../../ingress-traefik.yaml
  - ../../scale-policy.yaml
images:
  - name: harbor.iomio.io/library/media-stack-controller
    newName: harbor.iomio.io/library/media-stack-controller
    newTag: v1.0.120
patches:
  - path: demo-scale-patch.yaml
