apiVersion: v1
kind: Namespace
metadata:
  name: media-stack
  annotations:
    media-stack.io/author: Matthew Loschiavo
    media-stack.io/site: https://matthewloschiavo.com
    media-stack.io/contact: mploschiavo@gmail.com
    media-stack.io/linkedin: https://www.linkedin.com/in/matthewloschiavo
