apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-stack
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media-stack
spec:
  replicas: 0
